### ISSUE TITLE
No CMAKE_CXX_COMPILER could be found.

### ISSUE THREAD

**Issue by harishankar1014** [htm-community/htm.core#1005]
Hi, I am trying to execute the setup.py file. I have visual studio code 2022 installed with C++ CMake tools for Windows . However I am getting this error "No CMAKE_CXX_COMPILER could be found." Any suggestions?

**Comment by dkeeney** [comment]
Interesting...
I cannot duplicate your error, but perhaps the following will help:

1) Before doing a build, delete the entire build folder from the repository.  This contains a cache which can get messed up if you try to restart a failed build.

2) Make sure you have the latest version of CMake installed.  
   `  cmake -verision`
VS 2022 needs at least CMake 3.21.  The latest CMake version 3.25.0, generates a lot of depreciation warnings but it works.

If that does not work, run the following in a command prompt to confirm that VS2022 is there and accessable.
   `  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"`
This will generate a list of entries. One of them should be
     `   displayName: Visual Studio Community 2022`
If not, then check your VS2022 installation.
