### ISSUE TITLE
Separate NetworkAPI Module. 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#112]
> We also need to be sure this will work with my Array class (which is a container for SDR arrays being passed in the Link object. @dkeeney 

What do you think of separating also the NetworkAPI (region/, engine/) into a separate (optional) module/binding? 

### Module design

- Modules would be in `/bindings/{py, napi, cuda, tests, ...}`
- have explaining Readme
- separate CMake that is called hierarchically 
- `src/`
- separate namespace (eg `nupic::cuda, nupic::tests, ...`) 
- their build can be set by compile flags `-DNUPIC_TESTS, -DNUPIC_NAPI`) (napi & tests would be ON be default) 
- this includes files currently in src/nupic/{regions, engine} 

Just like Tests #91 
Part of #2

**Comment by dkeeney** [comment]
Well, the bindings along with all other python stuff should be separate,
yes.   But lets get rid of SWIG first.

**Comment by dkeeney** [comment]
I think we can call this one finished.

**Comment by dkeeney** [comment]
Well, There is a LOT of .py code that relies on the NetworkAPI.  The entire OPF framework for example.  The NetworkAPI is not bad once you start to understand how it works.

The NetworkAPI still contains a lot of ugliness and smelly code that I think we are now getting into a position to address. But I would still like to retain the framework for now.

At some point we will see some .py algorithm code that implements some of the Grid Cell and thousand brain things we have been hearing about.  At that point we can decide if the NetworkAPI still make since.

**Comment by breznak** [comment]
> The NetworkAPI still contains a lot of ugliness and smelly code that I think we are now getting into a position to address. But I would still like to retain the framework for now. 

No, I'm about to keep the NetworkAPI (I think it's the only API that is reasonably designed here)
I just suggest moving it to a module (which will be ON by default, same as PY). So in extreme cases/optimization, you can build core core (sic) separately. 
What do you think?

**Comment by dkeeney** [comment]
Well, I guess you could think of the algorithms as a collection of disjointed parts that could be used without the NetworkAPI.  But if the NetworkAPI were slimmed down and better described it could be used to provide a cleaner consistent and more understandable interface between all of the algorithm parts.  I think as port more .py code to C++ (TMRegion and SPRegion for example) it will be more obvious.

But better modularation of the NetworkAPI as a separate component is reasonable.  It's fairly separate already.  Perhaps building as a separate library.  Algorithms and engine.

**Comment by breznak** [comment]
> Well, I guess you could think of the algorithms as a collection of disjointed parts that could be used without the NetworkAPI. 

Yes, that is my intention with this issue. If you wanted to, say port HTM to some obscure architecture, you can use the very core first (algorithms/ engine/ math/ types/ ...) but keep the NAPI (regions/ engine/ ..?) out. 

NAPI literally is a binding to the "core" algorithms, that's why I like to think of it as a module on its own. 
All improvements etc to NAPI are still valid and useful, even when it's a module.

**Comment by dkeeney** [comment]
Ok, let me look at doing that.  Does not seem like it would be hard to make them separate libraries.

**Comment by dkeeney** [comment]
How about this for a layout:
```
Repository
  external
    
  bindings
    py
      packaging
      src
      test
      
  HTM
    examples
    src
      nupic
        algorithms
        encoders
        math
        utils
        types 
    test
    
  NetworkAPI
    examples
    src
      nupic
        engine
        ntypes
        os
        regions
    test
```

- types/Types.h and types/Types.hpp should be combined.  (do we still have C modules?)
- types/BasicType, ptr_types moved to nTypes/
- math/Types.hpp should have a different name or combined with types/Types.hpp.
- ntypes/SDR.hpp should be moved to types/
- engine would depend on HTM.  All of the regions depend on the algorithms in HTM anyway. 
- HTM would not depend on engine.
- Actually, may of the things in nTypes/ can be removed with a little thought.

We build the following libraries:
 - nupic.htm.a  static
 - nupic.engine.a  static
 - nupic.binding.engine.so 
 - nupic.binding.math.so
 - nupic.binding.algorithms.so

**Comment by dkeeney** [comment]
Maybe better:
```

Repository
  external
    
  bindings
    py
      packaging
      src
      test
      
  htm
    src
      examples
      nupic
        algorithms
        encoders
        math
        utils
      test
    
  netapi
    src
      examples
      nupic
        engine
        ntypes
        os
        regions
        types 
      test
```
The CMakeLists.txt goes under each src.

**Comment by dkeeney** [comment]
If I am going to do this it must be quick so that it does not held up anyone's PR's.
It is going to affect everything.

**Comment by breznak** [comment]
I’d keep current structure, just move regions, engine, os? Under bindings/
networkapi / src?

Types should remain in src/nupic to make it usable

Or is it all too much changes for too little benefit?
-- 
Marek Otahal :o)

**Comment by dkeeney** [comment]
> I’d keep current structure, just move regions, engine, os? Under bindings/ networkapi / src? 

Don't understand that....networkapi has nothing to do with bindings.
I view NetworkAPI, HTM Algorithms, and Bindings as sort of parallel things although you could think of it as the NetworkAPI is on top and HTM Algorithms and Bindings are subordinate things.  I think parallel makes the most since; with NetworkAPI dependent on HTM.  Bindings dependent on both.

> Types should remain in src/nupic to make it usable
I agree that types should stay with the HTM algorithms.

I am putting together a strawman that you can look at in the morning.

**Comment by breznak** [comment]
> although you could think of it as the NetworkAPI is on top and HTM Algorithms and Bindings are subordinate things. 

This is the way I was thinking.. I take
- "normal nupic" src/ 
- bindings/py
- bindings/napi

...making NetworkAPI at the same level as PY. (Although PY would have to provide bindings to both:core always, napi if compiled)

**Comment by breznak** [comment]
or a compromise? Leave files as is, and do in just in cmake? 
- compile nupic.core (core algs)
- compile nupic.napi (binds to nupic.core) 
  - this target can be optional (way to turn it off) 
- bindings/(py) would have to recognize if .napi exists and if it should provide bindings even for its classes.

**Comment by dkeeney** [comment]
We could turn off napi...if we moved a few components around I guess.  But just compiling htm and napi in separate libraries is doing about the same thing.  Either would be useful as a calling library for a C++ application.  
- Link to htm if you only want the algorithms and want to roll your own infrastructure.
- link to both to get the Network framework with the algorithms wrapped with regions as plugins.

The language bindings have two parts.  
- There are the bindings directly to the htm (algorithm.so, math.so) components.  
- There are the bindings directly to the napi (engine.so) components 
I don't know what value there would be in not generating one of the three libraries.

**Comment by dkeeney** [comment]
To repeat what I said in the PR...
Since there are so many differences of opinion as to what this repository represents lets put this PR on hold until we can decide what to do. 

Perhaps two separate repositories would be a better alternative. One for htm and one with the NetworkAPI, each with their own language bindings. I think we could do that without breaking the API.

Lets think about it.

**Comment by dkeeney** [comment]
We are going to leave this as-is.
