### ISSUE TITLE
Investigate: Connection use separate classes for Synapse, Segment, Cell

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#154]
Why? 
Allows reduction of Synapse, SynapseData, etc duplicits. 
Pairs logic and data correctly into classes. 
Allows reduction of some helper methods (Connections::compareSegments) to proper Segment::op== 

Cons: 
Measure potential slowdown, but lightly written classes should have almost none impact. 

Pros: 
Better structured logic, cleaner code. 
Makes code more similar to what's used in TP, Segments, Cells4, etc..(allowing eventually to implement TP-on-Connections? #95 )

After #93

**Comment by ctrl-z-9000-times** [comment]
So the types "Synapse" and "Segment" are 32 bit index / identifiers.  SynapseData and SegmentData are already classes (structs actually) and they are never duplicated or copied, instead their index is copied.

I agree that these classes could help better organize the code.

**Comment by ctrl-z-9000-times** [comment]
Another way to refactor the connections class would be to make an allocator for synapses and segments.  It would deal with the free lists and ordinals.  This should have zero performance impact, minor code de-duplication, no public API changes.  It would also provide a place to document how these types are used.

**Comment by ctrl-z-9000-times** [comment]
Consider that the synapse struct/class does not contain any pointers to the connections class, only indexes.  This is good because index is 32 bit versus pointer which is 64 bit, but it does force much code into the connections class even if logically it would make more sense for it to be in synapses class

**Comment by ctrl-z-9000-times** [comment]
Refactor: Connections::load should call createSegment & createSynapse instead of re-implementing those functions in-line.

**Comment by breznak** [comment]
TM is already using Connections. And Connections have now more sofisticated versions of Synapse,Segment, ... (still not a class, but SynapseData structure with constructor etc)
