### ISSUE TITLE
getOutputElementCount( ) vs getNodeOutputElementCount( )

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#189]
I noticed that the[ Nupic API documents](http://nupic.docs.numenta.org/stable/api/network/regions.html) and all of the .py code uses getOutputElementCount( ) as the function to get the width of an output buffer.  However, in C++ it is called getNodeOutputElementCount( ).

Does anyone know the story behind this?
Should we change the C++ side to match the .py side?

**Comment by Thanh-Binh** [comment]
I do not know the story, but I think the function name in c++ is more precise than in python

**Comment by breznak** [comment]
Not sure about which side to choose, but we should choose one. 
There's a test failing: 

```
========== FAILURES ==========================================================================================
_________________________________________________________________________ NetworkTest.testNetworkLinkTypeValidation _________________________________________________________________________

self = <tests.network_test.NetworkTest testMethod=testNetworkLinkTypeValidation>

    def testNetworkLinkTypeValidation(self):
      """
        This tests whether the links source and destination dtypes match
        """
      network = engine.Network()
      r_from = network.addRegion("from", "py.LinkRegion", "")
      r_to = network.addRegion("to", "py.LinkRegion", "")
>     cnt = r_from.getOutputElementCount("UInt32")
E     RuntimeError: Attribute getOutputElementCount not found

../../bindings/py/tests/network_test.py:160: RuntimeError
===================================================================== 1 failed, 151 passed, 31 skipped in 1.17 seconds =======
```

**Comment by dkeeney** [comment]
I recommend changing the C++ code to match the API documentation and .py code.  We control the C++ side.  We do not control the .py side.

**Comment by breznak** [comment]
nit, how come the test fails on me locally, but our CI is passing??

**Comment by breznak** [comment]
I think this has been resolved (?)
