### ISSUE TITLE
Security CVE in numpy version

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#227]
There's security problem in our version of Numpy's pickle, 
https://www.bleepingcomputer.com/news/security/numpy-is-awaiting-fix-for-critical-remote-code-execution-bug/ 

We should bump to 1.17 once it's available on PyPI!

**Comment by ctrl-z-9000-times** [comment]
I noticed this in the release notes for numpy 1.16.0
> Future changes
> NumPy 1.17 will drop support for Python 2.7.

https://docs.scipy.org/doc/numpy/release.html

**Comment by breznak** [comment]
Closing, we're now using `numpy 1.18.x`
