### ISSUE TITLE
Connections - Python Bindings

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/htm.core#243]
Python should be able to use the C++ Connections class.  This is important for experimentation, to combine the ease-of-use of python with the speed of C++.

Results:
* Python user can create, setup, and run the connections in a simple example.
* Python user can manipulate synapses, segments, cells & all of their data fields.
* Python connections module should be easy & intuitive to use.

**Comment by breznak** [comment]
I'm :-1: , not that I mind if you want to implement this, but imho this is exposing a low level API (and we don't want to stabilise that?) 

Is this really needed? 
- Py users can have native python `connections.py` for experimentation, visualization, etc
- There are py bindings for Spatial pooler, Temporal memory, the main (only) users of Connections.hpp 
- NetworkAPI does not need that either. 

It is the same situation as when SparseMatrix* classes was exposed to python, it is just a backend. 
If you still do find it useful, I don't mind, just please document that API may break for Connections.

**Comment by ctrl-z-9000-times** [comment]
This is something i will probably discuss more after the survey closes and we start planning which features to support.  

For experiments which modify the algorithms, IMO, the connections python bindings are more useful than the SP or TM in pure python.  This would allow python users to make a new algorithms which run as fast as in C++ since the connections class does the heavey lifting.

**Comment by ctrl-z-9000-times** [comment]
I found a need for python binding for connections class:
Id like to write a program which loads a connections object from file and analyizes it.  This can not be done in C++ because i want it to plot graphs and do anaylsis which C++ is ill suited for.  Id like to see:
- Histogram of segments per cell,
- Histgram of synapses per segment
- Histogram of synapse permanences, with threshold indicated.

**Comment by breznak** [comment]
>  found a need for python binding for connections class: 

ok, let's go on with that :smiley:  
Please, put a warning that Connections is not a part of the API and may freely change, I think that should be enough

**Comment by ctrl-z-9000-times** [comment]
### Desired changes to the Connections Python bindings
 * I'd like to wrap the SegmentData & SynapseData classes, and for those wrappers to contain pointers back to the Connections object. This way python users can treat segments and synapses as objects instead of the current: as integer handles into a connections object.
   - Example current API: `connections.updateSynapsePermanence(synIdx, newPerm)`
   - Example desired API: `synapse.updatePermanence(newPerm)` which inside of the pybinding code will call the current API.

 * I'd like to provide Numpy array interfaces for methods which are typically called every compute cycle, with the goal of python calling them once per compute cycle. Currently these need to be called once per segment, they should be called once with an array of segments.
   - adaptSegment
   - raisePermanencesToThreshold
   - bumpSegment

Maybe also modify the C++ code?
>  I would like the change even in c++, for the low-level methods to take (sparse) vector, instead of a single integer (index). This would move the loops to a higher code.
>  breznak

**Comment by breznak** [comment]
Closing, as this has been merged sometime already.
