### ISSUE TITLE
Serialization: include helpers from StlIo.hpp, cleanup StlIo drastically

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#266]
- include StlIo.hpp with Serializable.hpp 

- keep binary_save
- maybe store_vector
- remove rest
- cleanup custom developed helpers in each file using Serialization, use these common helpers.

**Comment by dkeeney** [comment]
I think that binary_save and store_vector are used in one or two places in save( ) and load( ) but I don't like the idea of cluttering up Serializable with them.

Actually, I have been thinking a lot about serialization lately.  I think we are going about it wrong.  It seems to me that the ONLY thing that needs to be serialized are the parts of the algorithms that are learned.  If the idea is to restart a test continuing on with previously learned state then we should not need to save anything other than learned state...everything else should be re-created when the test is restarted.  Even the parameters do not need be saved unless it affects the ability to resume with a previously learned state.  

For NetworkAPI we probably need to save the arrangement of connected regions so there is something to hang the learned state on, but nothing more.

Anyway, just a thought.

**Comment by breznak** [comment]
>  serialization lately. I think we are going about it wrong. It seems to me that the ONLY thing that needs to be serialized are the parts of the algorithms that are learned. 

could you give a more specific example? I think this is what we are doing now. With a grain of salt, we don't have to serialize a const, but we need to store the param. How would you know the value on a fresh restart? 

On loading code depends the balance: to more you binary store, the less complex the reinitialization/load needs to be. 

> but I don't like the idea of cluttering up Serializable with them.

I know what you think, we cannot provide a cook-recepie for every data type one might store, but I've seen @ctrl-z-9000-times use a lambda to store vectors recently, StlIo has binary_save, vector<T>, I've done a for loop for storing vectors, maps in Classifier.... I think the vector is an all-around candidate that could be there. 

> just a thought. 

this also led me to a thought, could have nta_assert which checks that the load restors the object correctly 
```
void save() {

 #if debug
  auto stored = load(..)
  NTA_ASSERT(this->equals(stored));
}
```

**Comment by dkeeney** [comment]
>  but we need to store the param. How would you know the value on a fresh restart?

I don't think so.  You might need the buffer width (dimensions) for the stored state.  But everything else should be changeable, no?   In fact the reason to restart might be to change the parameters, thresholds, etc.

The point I am making is that instead of saving every variable in every class we should see if we can save only those that relate to the state of things that were 'learned'.  If an algorithm is not in learning mode, there would be nothing to save.  Obviously there would need to be a different mechanism for saving and loading and that would take some time to think through.

For example, an SP, I would think that saved state would be the connections (id to id) and the permanence on each connection.  When we restart, we would create the SP and then allocate all of the connections from the learned state that had been saved.

The serialization we have now is just too slow to be useful for anything important.  Maybe saving only the learned state would make this less of a problem.

**Comment by ctrl-z-9000-times** [comment]
> The serialization we have now is just too slow to be useful for anything important.

I disagree.  It seems fast enough to me.  Do you have any evidence to back this up, such as for a typical network:
  * How long does it take to save & load?
  * How long _should_ it take to save & load?

**Comment by dkeeney** [comment]
Ok, I admit it is just my impatience.  
At some point I would like to put together a network of 100 hotgym's and see how it feels.

**Comment by breznak** [comment]
Cleanup and removal from StlIO done in #303

**Comment by dkeeney** [comment]
Someplace there was some discussion about Cereal package for serialization.  I could not find it (was probably in a closed PR) so I will add some discussion here.   I was thinking about getting started with this and wanted to be sure we were all on the same page.
- is this the next highest priority item for me?   Or should I be looking at some more region plugins?
- I do not want to do all of this in one go.  So I thought I could do one PR for one class...or maybe a small related set of classes at a time so this is spread over several PR's.
- The send(ostream f ) and load(istream f) functions will change signature to send(Archive& ar) and load(Archive& ar).  This means that I could add the new functions along side the existing ones until all Serializable items are completed and then remove the old ones.
- We want to not break any existing serialization until the new one is in place.
- Proposed Strategy:  
  - Go through all Serializable classes and add the new functions with a set of related PR's.  
  - Connect up this serialization to pickle interfaces.
  - Switch our Overall serialization (in Network) to the new functions.  Switch the Serializable class to use the new functions. Actually get a top to bottom serialization working.
  - Do a second pass and remove the existing send(ostream ) and load(istream ) functions and refocus the operator<< and operator>> overloads to use the new functions.

**Comment by breznak** [comment]
the idea is here: 
https://github.com/htm-community/nupic.cpp/pull/308#issuecomment-471013220 

demo 
https://github.com/htm-community/nupic.cpp/pull/308#issuecomment-473568273

**Comment by ctrl-z-9000-times** [comment]
I agree with this overall strategy. 

> priority item

I think the first priority is to get the library downloaded into the external directory.

> The send(ostream f ) and load(istream f) functions will change signature to send(Archive& ar) and load(Archive& ar).

Overloading probably won't work.  For my prototype: I had to make **cereal** rename the save & load methods, a feature which it supports!  After we've gotten the whole library switched to **cereal** we can have a big flag-day PR which switches from the old to the new.

> Do a second pass and remove the existing send(ostream ) and load(istream ) functions and refocus the operator<< and operator>> overloads to use the new functions.

I like save & load.  IMO  `<<` should be for the human readable versions.

**Comment by dkeeney** [comment]
> I like save & load. IMO << should be for the human readable versions.

Agreed.  My thinking was that << would call save( ) with the human readable Archive object.  Our archiving serialization would normally use the binary Archive object.  So with one set of save( ) and load( ) functions we get both a human readable output and a binary output.

It is interesting that you had to rename the save & load.  The Archive object must be a subclass of iostream.

**Comment by dkeeney** [comment]
So, I will get started on this and in the process of adding Cereal we can fix the python pickle interface.

**Comment by breznak** [comment]
Now that we use Cereal, can StlIo be removed completely?

**Comment by dkeeney** [comment]
I would expect that there are places where serialization of stl containers is still required for error messages and human readable streaming.  But you can check.
