### ISSUE TITLE
A NetworkAPI region for SDRClassifier algorithm

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#309]
I would like to create a new NetworkAPI plugin for the SDRClassifier algorithm.  Perhaps call it `ClassifierRegion`.

Right now, the only way to call this with NetworkAPI is via the .py code.

We will need:
- ClassifierRegion.cpp
- ClassifierRegion.hpp
- ClassifierRegionTest.cpp

**Comment by breznak** [comment]
This has been done by @dkeeney :+1:
