### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/htm.core#325]
We currently use **doxygen** to automatically make pretty html webpages.  Doxygen scans the sourcecode for specific tags, which are used inconsistently.

Doxygen Homepage: http://www.doxygen.nl/index.html
Doxygen Primer: https://github.com/osue-tuwien/osue-tuwien.github.com/wiki/Doxygen-Primer

TODO:
- [ ] Add section to README describing how to build documentation.
    * `cd docs ; doxygen`
- [ ] Add the doxygen tags to the in-line comments in the source code.
- [ ] Python bindings need docs and have none.  Doxygen claims it can work with python, and there are several other python solutions as well.  The easiest is the builtin `pydoc` module, see `python -m pydoc --help`

**Comment by ctrl-z-9000-times** [comment]
It might be nice to have a glossary of commonly used terms?  Many of these definitions could be copied from the existing documentation.

If I wrote it I would start with the following words which describe encoders:
- radius
- resolution
- size
- activeBits
- sparsity
- seed

And I would put it in the python module documentation.

**Comment by dkeeney** [comment]
This sounds like a reasonable thing to do.  

I have been thinking about the documentation.  I am wondering if we should have two sets... one for C++ call interfaces and one for Python interfaces.  Although the Python docs would be similar to the offical numenta documentation we should probably have our own version of both python and C++ docs in the wiki.  I don't consider doygen to be documentation; they never tell me anything I cannot get by just reading the code so why bother. We need something to tell people what the exposed calls are for and how to use them.

Anyway, just my thoughts.

**Comment by ctrl-z-9000-times** [comment]
IMO we should document how to use this library, but not document how the HTM theory works.  It's complicated and other people have already explained it better than I can.  Instead we should find and link to the best explanations.
- Numenta's peer reviewed / white papers
- HTM School videos

**Comment by dkeeney** [comment]
Adding Doxygen comments consistently  everywhere would help to define the details but do we also need more over-all documentation someplace similar to the Numenta docs? http://nupic.docs.numenta.org/stable/index.html  Something that defines our API?

**Comment by breznak** [comment]
> but do we also need more over-all documentation someplace similar to the Numenta docs 

this would be nice, but unless you want to do that I don't consider it necessary at this point. For now I'd stict to a good code documentation + example & unit test coverage

**Comment by breznak** [comment]
A high level documentation in a form "what is HTM and what does this repo do?" was mentioned in the thread above, and I'd like to improve that as a part of submission to  JOSS paper https://joss.readthedocs.io/en/latest/submitting.html which is a follow-up to #729

**Comment by dkeeney** [comment]
That would be a cool thing to have but that is not what I am thinking of here.  I think we need something that describes how to use this software.  The 'How' not the 'Why'.  Thinking of our repo as a tool, what are the mechanics of using it.  Specifically the NetworkAPI.  

The mechanics of using the algorithms are rather straight-forward.  You call an entry point with some parameters and it performs the functions described in the white papers.  Not much to say other than what are the parameters and all of that can be described in the comments in the code.

The NetworkAPI needs a little more explanation about how to declare the Regions and how to set up the flow of data between them.  But 'why' someone might want to have some Regions and  data flows is another topic that is beyond the mechanics of setting it up.

Now, having said that, I think it would be really interesting to write a paper about the 'why' and show some of the cool things that could be done with this tool and why this is important. But that is a separate document.

**Comment by breznak** [comment]
> That would be a cool thing to have but that is not what I am thinking of here.

yes, what I intend is a slightly OT, as a more high level intro/doc. 
I think we need 3 sections/types of documentation for: 
- researcher : mostly links to htm papers, and examples of active research topic in the repo
- newcomer : description of what are we about here. My intend for the first JOSS paper
- app developer: (I know enough of what HTM does), how do I use it in my cool project X? 

> The NetworkAPI needs a little more explanation about how to declare the Regions and how to set up the flow of data between them

I think the NetworkAPI demo (there's issue for that) is a good starting point, I think some demos are by Matt (videos, HTM schools?)

**Comment by breznak** [comment]
doxygen done in #803 , thanks @johanwiden :+1:
