### ISSUE TITLE
Connections: optimize data types' cache utilization: half, float16

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#360]
After typedefs from PR #331 are merged to Connections: 

- [ ] experiment with smaller data-types for better CPU cache utilization
  - [ ] other thing is auto-vectorization/SIMD which uses int32,float
  - [ ] try half_t float16 for Permanence
- [ ] add ConnectionsPerformance test using valgrind  CacheGrind to actually measure cache use
  - [ ] for hotgym (SP, TM)
  - [ ] MNIST (SP, CP)

Ref: #161

**Comment by breznak** [comment]
working-group paper in half, float16_t for C++ standard, hopefully it'll be standardized soon (not really soon) 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0192r4.html

**Comment by ctrl-z-9000-times** [comment]
Another idea for optimizing the connections: use fixed point arithmetic for the permanence values.  This should not be too hard because all the the floats are in the range 0-1 so the denominator will always be 2^16

**Comment by breznak** [comment]
> use fixed point arithmetic for the permanence values 

I was thinking about this, using unsigned char and instead of float "values" have differences simply. 
Such solution is available right now, a small disadvantage would be that all "compute" libraries (CUDA,...) use floating point math, so I'd be nice to stay on the same. 
Another question is if SIMD,AVX,auto-vectorization supports chars, as opposed to floats. 

But it'd be 4x lighter on cache, so worth a try!

**Comment by breznak** [comment]
Update: 
I'm considering `bfloat16` type from tensorflow, which as implemeted all the arithmetical conversions for bfloat16 & conversion to/from float
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/bfloat16/bfloat16.h 
https://stackoverflow.com/questions/55253233/convert-fp32-to-bfloat16-in-c

**Comment by breznak** [comment]
... and see how https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/bfloat16.h is different?

**Comment by breznak** [comment]
I have done preliminary experiments with: 

- `Permanence = char` in Connections.cpp -> no mem or performance gains
- `Permanence = float16` (actually Eigen::half) -> slower performance on CPU https://github.com/etaler/Etaler/issues/12#issuecomment-514247028 

Therefore summary for this issue is: does not bring any gains, likely actually slower. On CPUs, until there's float16 HW support. Closing
