### ISSUE TITLE
Add readme to build/Release/ to explain each folder

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#368]
> ls ../Release/*
../Release/bin:
benchmark_hotgym  mnist_sp  unit_tests
../Release/distr:
build  dist  dummy.c  requirements.txt  setup.py  src
../Release/include:
CSV_README.md  csv.h  nupic  src
../Release/lib:
libnupic_core.a  libnupic_core.so

This should be a `.md` file added to the Release during install from CMake

**Comment by ctrl-z-9000-times** [comment]
> ls ../Release/*
../Release/bin:
benchmark_hotgym mnist_sp unit_tests
../Release/distr:
build dist dummy.c requirements.txt setup.py src
../Release/include:
CSV_README.md csv.h nupic src
../Release/lib:
libnupic_core.a libnupic_core.so

These files are documented in the main `README.md` or in the `bindings/py/README.md`

But:
   - bindings/py/README is incomplete
   - /bin contents are documented all over the place, should be reviewed in one place.

I will resolve these issues in PR #526
