### ISSUE TITLE
Support for MSVC 2019

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#410]
Now that Visual Studio 2019 is out  I need to see if we need to modify our CMake to support it.

**Comment by breznak** [comment]
We can then update the CI to run the latest

**Comment by dkeeney** [comment]
I was looking for my next project and thought providing support for MSVC 2019 might be useful.  Also, perhaps "Visual Studio Code" which is a new IDE that runs on any platform.

Is there something else that might be higher priority?

**Comment by breznak** [comment]
Fixed in #568

**Comment by breznak** [comment]
> Is there something else that might be higher priority? 

great job on the new MSVC! 

I think next great thing would be binary releases (for C++ here on GH, and on pypi). Then installation for non-developers would be a piece of a pie. #361  #19  
I don't know if you want to look into that?

**Comment by dkeeney** [comment]
Ok, I don't know much about pypi but I can go read up on it.

**Comment by breznak** [comment]
> much about pypi but I can go read up on it. 

awesome! First step would be binary releases of C++ anyway. Ideally on GH. The remains of it are commented out in the CI files. I'd start with Travis, or Appveyor if you're using Windows. 

https://docs.travis-ci.com/user/deployment/releases/
