### ISSUE TITLE
Add support for frameworks.OPF from python

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#459]
OPF support for our repo, that means swarming (parameter optimization), and describing HTM models in JSON. 

This might be a lot of code! Although I don't expect any complications with removed c++ code dependencies (like SparseMatrix). 

This would make running NAB #205 rather easy. 
PR #433 is a different approach to parameter optimization (nupic calls it swarming).

**Comment by breznak** [comment]
Some valuable info! 

> No we are not committed to the OPF at all. It is an outdated interface. I think there is a place for something like the OPF, but it should be re-thought from scratch for a particular domain problem. ~Matt

https://discourse.numenta.org/t/sdrclassifier-returning-confidence-of-nan/5972/8?u=breznak 

I'd like to use this information two ways: 
> This would make running NAB #205 rather easy. 

Simply merge all needed OPF python code, for short term (well, we never know) support of things like NAB, htm.research. Without much love or care in fixing the code, rewriting to c++, just merge what exists, trying to minimize the code by using our bindgins api where possible (and easy). 

> PR #433 is a different approach to parameter optimization (nupic calls it swarming). 

and do not block any alternative ways for doing param. optimization. So ACK :+1:

**Comment by ctrl-z-9000-times** [comment]
> PR #433 is a different approach to parameter optimization (nupic calls it swarming).

Point of clarification: parameter optimization refers to the general process of finding good arguments for a program.  Swarming is a specific technique for doing so.  PR#433 uses a different technique known as "grid search".

**Comment by dkeeney** [comment]
Along the lines of getting a machine readable set of parameters... 
NetworkAPI contains a facility for reading YAML (and JSON) structures and uses these to override the default parameters for a region.  It would not be too hard to expand this facility to include the entire Network.  One file containing all of the parameters for a network. This could then be used as the parameter store for some sort of swarming.... just a thought.

**Comment by breznak** [comment]
> OPF support for our repo, that means swarming (parameter optimization), and describing HTM models in JSON. 

probably not, OPF was deprecated by numenta. We already have swarming, NAB etc running with the new htm.core codebase.
