### ISSUE TITLE
Implement NetworkAPI example 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#460]
A user is having a problem with SDRClassifier on numenta's, we'd like to replicate the provided experiment (runnable source code and data here https://github.com/numenta/nupic/issues/3875 ) 

This way we can 
- [ ] validate our Classifier has/not the bug? 
- [ ] have a working NetworkAPI Hotgym example, related #30 

Related c++ Classifier region https://github.com/htm-community/nupic.cpp/issues/309 , but this is not required, as the example runs python.

**Comment by breznak** [comment]
CC @dkeeney

**Comment by dkeeney** [comment]
> we'd like to replicate the provided experiment

I can add this to my plate but I cannot do any work until this weekend, after my guest leave.
Should not be difficult to make a NtworkAPI version of hotgym if we had the right encoder and a classifierRegion ... something like
```
Network n;
n.addRegion("encoder", "RandomDistributedScalarEncoder");
n.addRegion("SP", "SPRegion");
n.addRegion("TM", "TMRegion", "parameters go here");
n.addRegion("Classifier", "ClassifierRegion");
n.link("encoder", "SP");
n.link("SP", "TM");
n.link("TM", "Classifier");
n.run(EPOCHS);
```

Not quite as simple as that because we need to specify the non-default parameters but you get the idea.

**Comment by breznak** [comment]
> Should not be difficult to make a NtworkAPI version of hotgym if we had the right encoder and a classifierRegion 

Perfect. I was hoping if the orig author would be interesting in contributing the code, but we'll see. 
The example is in python, so I was hoping we use python Regions (=no need to write SDRClassifier c++ region), and encoders (either from bindings, or I'll port them #462 ) 

Also, hotgym needs only anomaly, no?

**Comment by dkeeney** [comment]
>  I was hoping we use python Regions ...

yes, we can use Python Regions.  That would be simpler if they have been converted to Python3.
Eventually I do want to write a ClassifierRegion so C++ only folks will have a classifier.

> Also, hotgym needs only anomaly, no?

Oh, of course.  So we don't even need the classifier for this.  Only an encoder Region and that can be in Python. All we need to do is register the python region with Network.

**Comment by Thanh-Binh** [comment]
@dkeeney Did you write C++ ClassifierRegion? If yes, where can I find it? Thanks

**Comment by breznak** [comment]
> Did you write C++ ClassifierRegion? If yes, where can I find it? 

it would be in `src/htm/regions/`, so not yet.

**Comment by dkeeney** [comment]
> Did you write C++ ClassifierRegion? If yes, where can I find it?

We would love to have one.  Would you be willing to build it?

**Comment by breznak** [comment]
We have `napi_hello` example which does that :+1:
