### ISSUE TITLE
Python MNIST examples: data not available out of the box

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#514]
I'd like to make the MNIST python example runable out of the box. 

it expects manually downloaded file MNIST_data/, 
instead:
- use existing `build/ThirdParty/mnist_data/mnist-src/` which is downloaded for the c++ example 
- or use `sklearn.datasets` 
https://scikit-learn.org/0.19/datasets/mldata.html 

I'd prefer the sklearn method, for it allows an easy way to test on other popular image classification data, 

Some possible additional steps: 
- rename file from mnist to image_classification.py 
- decouple names from the mnist use-case, make more generic & useful 
- try with other datasets: iris, cifar, fashion-mnist, ... 
  - provide optimized params for each of them (?)

**Comment by ctrl-z-9000-times** [comment]
sklearn is would be good for this task.

I do not think that the MNIST example code is suitable for any data set other than MNIST.

**Comment by ctrl-z-9000-times** [comment]
thanks for working this issue Breznak!

**Comment by breznak** [comment]
> or use sklearn.datasets
https://scikit-learn.org/0.19/datasets/mldata.html

I'll reopen the issue temporarily, might have someone interested in fixing the `sklearn datasets` support, which would be optimal solution. If not, we close this as "good enough" later.

**Comment by crimsoncress** [comment]
Hello, I'm new in the field of htm, I'll try to solve this issue, but might need help. Thanks!

**Comment by breznak** [comment]
Hi, sure, go ahead and ask if you need something. 
The py code you'll be looking at is https://github.com/htm-community/htm.core/blob/master/py/htm/examples/mnist.py 
And. Welcome. To. The. Party.

**Comment by breznak** [comment]
alternative to consider is 
https://pypi.org/project/tensorflow-datasets/ 

see if any of the 2 libraries is better (more datasets, nicer API, ...) TF seems pretty active.
