### ISSUE TITLE
Rename the repo to ??? 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#524]
With the ongoing changes (#518 ) to uncouple htm from the NuPIC (tm), we should rename the repo. 

What is the agreed name? 
- htm.cpp ? 
- htm + something with community ?

**Comment by Zbysekz** [comment]
I think if there is a plan to keep py code within this repository (i mean not bindings, but the py redundant code), then it would **not** make sense to name it htm.cpp, do you agree?
* What about htm-framework ?

**Comment by ctrl-z-9000-times** [comment]
Some more ideas for names:
- nupic.redux
- htm.ce (for community edition)

**Comment by breznak** [comment]
- htm.community (rather than ce?, but I also like the community in the name) 
- htm.core
- htm.bindings   ?

**Comment by dkeeney** [comment]
My vote is for htm.core.

**Comment by Zbysekz** [comment]
I am also for htm.core. Sounds cool

**Comment by ctrl-z-9000-times** [comment]
My vote is for htm.community

**Comment by ctrl-z-9000-times** [comment]
The current tally is:
- 2 votes for htm.core (@dkeeney, @Zbysekz )
- 1 vote for htm.community (@ctrl-z-9000-times)

@Breznak, @rhyolight, Do you have a preference for the name?

**Comment by breznak** [comment]
between these 2 I'm for htm.core (because we have the htm-community prefix), no hard feelings about the name though
