### ISSUE TITLE
Release Soon

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/htm.core#529]
I'd like us to release this soon.  It may not be 100% done, but I don't think anything is ever 100% done.

I've drafted a forum post, what do you all think?
(I will fill in the repo name & URL after issue #524 is dealt with)

---

Subject: HTM.Core Release Announcement

Hello Everyone,

We're proud to announce the first release of the "HTM.Core", the HTM-Community's successor to the NuPIC.core library.  Although this library started as a fork of Numenta's NuPIC.core, we've changed many things and so we've also changed the name to "HTM.Core".  We have made a large number of improvements to NuPIC with the goals of making it easier to use and faster to run. For instructions on how to use this software, visit our github page: https://github.com/htm-community/htm.core

This is a collaborative effort. If you have a question, encounter a problem, or have an idea for how to improve this software, then please tell us about it on our github page or on this forum.

Thank you,
Breznak,  Dkeeney, Dmac, and everyone else who contributed.

**Comment by dkeeney** [comment]
Yes, I like it.   Are we going to rename the repository first?

**Comment by ctrl-z-9000-times** [comment]
> Yes, I like it. Are we going to rename the repository first?

IMO If we're going to rename it then we should do it before we release the software. Now or never?

**Comment by breznak** [comment]
:+1:  to the rename. 
I like the text, thanks. 
Two more options that I think should be done before release are related to packaging: 
- binary releases (on GH), I got stuck on this, we need @rhyolight or sb who's done it to help us here 
- and pypi package

**Comment by ctrl-z-9000-times** [comment]
While I think having distributable packaging would be great to have, I don't see it as critical for releasing since we have good instructions on building from source.

**Comment by ctrl-z-9000-times** [comment]
Posted: https://discourse.numenta.org/t/htm-core-release-announcement/6223
