### ISSUE TITLE
branch cleanup

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#538]
There are a number of branches in the repository that should be deleted. Those that I am aware of that are either abandoned or completed are:
- NetworkAPI_module
- Add_SDR_to_Array
- cereal-spec
- networkapi
- yamlProblem

I dont' know the magic incantation needed to remove them.
@breznak when you find time can you remove them for me?

**Comment by dkeeney** [comment]
Oh, yamlProblem is for PR #282.    I should probably try to find a workaround for that.   So leave that one.

**Comment by ctrl-z-9000-times** [comment]
Click on the circled button:

![Screenshot from 2019-07-03 11-04-01](https://user-images.githubusercontent.com/19578795/60602779-77a32280-9d82-11e9-83ca-3fb518dea1c8.png)

**Comment by breznak** [comment]
I cleand a few that were closed, now we're at 20, 17 of it is open PRs.
