### ISSUE TITLE
cant find pluggy dependency

### ISSUE THREAD

**Issue by sublimemm** [htm-community/htm.core#554]
Installed c:\users\sub\appdata\roaming\python\python37\site-packages\htm.core-1.0.8.community0-py3.7-win-amd64.egg
Processing dependencies for htm.core===1.0.8.community0
Searching for pluggy<1.0,>=0.12
Reading https://pypi.org/simple/pluggy/
Download error on https://pypi.org/simple/pluggy/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
Couldn't find index page for 'pluggy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
No local packages or working download links found for pluggy<1.0,>=0.12
error: Could not find suitable distribution for Requirement.parse('pluggy<1.0,>=0.12')

**Comment by sublimemm** [comment]
i think this may be related to pip or the pluggy repo in particular...



E:\numenta\htm.core>pip install pluggy
Collecting pluggy
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pluggy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pluggy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pluggy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pluggy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pluggy/
  Could not find a version that satisfies the requirement pluggy (from versions: )
No matching distribution found for pluggy

E:\numenta\htm.core>

**Comment by breznak** [comment]
Hi, this is likely won't fix, as we do not directly require `pluggy`, it is a dependency of some other dependency. 

> Reading https://pypi.org/simple/pluggy/
Download error on https://pypi.org/simple/pluggy/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!

this looks like your internet connection is flanky, or some err with pip? 

- I'd suggest a clean build

**Comment by sublimemm** [comment]
yep. anyone using the Killer Wireless Network drivers apparently has this issue. Either remove them or upgrade to the latest version. all is working now.
