### ISSUE TITLE
Swarming: fails sometimes on "Unrecognized parameters"

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#570]
Running 

>  python -m htm.optimization.ae -n 7 --memory_limit 14 -v --swarming 10  mnist.py

Sometimes it fails on me with 

> Lab Report written to mnist_ae/lab_report.txt
New global best score 0.9622.
New particle best score 0.9622.
/mnt/store/devel/HTM/pyenv3/lib/python3.6/site-packages/numpy-1.17.0rc1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:3506: RuntimeWarning: Degrees of freedom <= 0 for slice
**kwargs)
/mnt/store/devel/HTM/pyenv3/lib/python3.6/site-packages/numpy-1.17.0rc1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
New particle best score 0.9595.
New particle best score 0.9612.
New particle best score 0.96.
New global best score 0.9621.
New particle best score 0.9621.
New particle best score 0.9607.
New global best score 0.9628.
New particle best score 0.9628.
New particle best score 0.9607.
New particle best score 0.9612.
New global best score 0.9631.
New particle best score 0.9631.
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/mnt/store/devel/HTM/pyenv3/lib/python3.6/site-packages/htm.core-1.0.8.community0-py3.6-linux-x86_64.egg/htm/optimization/ae.py", line 656, in <module>
memory_limit = memory_limit,)
File "/mnt/store/devel/HTM/pyenv3/lib/python3.6/site-packages/htm.core-1.0.8.community0-py3.6-linux-x86_64.egg/htm/optimization/ae.py", line 463, in run
self.method.collect_results( X.parameters, trial.score )
File "/mnt/store/devel/HTM/pyenv3/lib/python3.6/site-packages/htm.core-1.0.8.community0-py3.6-linux-x86_64.egg/htm/optimization/swarming.py", line 180, in collect_results
raise Exception("Unrecognized parameters!")
Exception: Unrecognized parameters!

And the whole process stops.

**Comment by breznak** [comment]
CC @ctrl-z-9000-times

**Comment by ctrl-z-9000-times** [comment]
Breznak,

That line should only be reached if the is an internal logic error in the program.  I think it's caused by a concurrency issue where two threads modify the same particle.  I will see if I can fix it.

**Comment by breznak** [comment]
> caused by a concurrency issue where two threads modify the same particle.
I will see if I can fix it.

Seems likely, I hit that when running a few particles. 7:7
Thank you for looking into it, even a clearer failure “some concurrency
problem, use more particles to reduce the chance to cause this “ would
help, if you don’t manage to find a proper fix

-- 
Marek Otahal :o)
