### ISSUE TITLE
Error linking by Ubuntu boost ....

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#585]
Hi developer,
I am testing htm.core by a standalone application outside of htm.core and have the following linking problem, where the 3rd party library like Boost is not found in "libhtm_core.a".
I think more about a bug by fusion all libraries.
What do you think?
```
CMakeFiles/testEncoder.dir/apps/test/testEncoder.cpp.o: In function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
testEncoder.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x40): undefined reference to `boost::system::generic_category()'
testEncoder.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xb9): undefined reference to `boost::system::generic_category()'
testEncoder.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x111): undefined reference to `boost::system::generic_category()'
CMakeFiles/testEncoder.dir/apps/test/testEncoder.cpp.o: In function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
testEncoder.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0x3b): undefined reference to `boost::system::generic_category()'
testEncoder.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xa1): undefined reference to `boost::system::generic_category()'
CMakeFiles/testEncoder.dir/apps/test/testEncoder.cpp.o:testEncoder.cpp:(.text.startup+0x3b): more undefined references to `boost::system::generic_category()' follow
CMakeFiles/testEncoder.dir/apps/test/testEncoder.cpp.o: In function `_GLOBAL__sub_I__ZN3htm4RdseC2ERKNS_14RDSEParametersE':
testEncoder.cpp:(.text.startup+0x45): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
```

**Comment by breznak** [comment]
Hello, 
this is likely issue with your custom application (are you linking correctly?)

As htm.core uses boost (even if limited subsection boost::filesystem) in some cases (it does not link boost if c++17 is found (that means g++ >= 8, linux, ...)) 

> problem, where the 3rd party library like Boost is not found in "libhtm_core.a".

htm.core does not (necessarily) provide boost. 

What you could try is forcing boost with `cmake -DNEEDS_BOOST=1 ......`

**Comment by Thanh-Binh** [comment]
@breznak I try to use gcc-8, but have the same error.
Could you please explain me why htm.core needs boost? Thanks

**Comment by Thanh-Binh** [comment]
@breznak I have just compiled htm.core with the option NEEDS_BOOST=1 as you recommend. But my application can not be linked with boost and have the same errors.

**Comment by breznak** [comment]
>  try to use gcc-8.3, 

gcc 8.3 (and other compatibilities to c++17 should be fine), if boost is not used, you'll see 

> $ cmake ../.. -DCMAKE_BUILD_TYPE=Release
-- REPOSITORY_DIR       = /mnt/store/devel/HTM/htm-community/nupic.cpp
-- CMAKE_BINARY_DIR     = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/scripts
-- CMAKE_BUILD_TYPE     = Release
-- CMAKE_INSTALL_PREFIX = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/Release
-- FORCE_CPP11          = OFF
-- FORCE_BOOST          = OFF
-- BINDING_BUILD        = Python3
-- Environment var CXX  = g++-9

> compiling htm.core failed due to the 3rd party lib like YAML.

you need to rm all the `build/ThirdParty` if you change compiler version, cmake does not trigger rebuild of ThirdParty dependencies, so that might be your problem. 

> Could you please explain me why htm.core needs boost? 

I thought you need/use boost in your application from the example? 
htm.core does not need boost if `std::filesystem` can be used (c++17, g++-8+), otherwise `boost` is required for Serialization. 

> I have just compiled htm.core with the option NEEDS_BOOST=1 as you recommend. But my application can not be linked with boost and have the same errors.

so either your application needs boost by itself, and then you need to provide linking,includes to its build. 
Or if the app does not (?) require boost, you should be fine with the advice above and rebuilding without boost at all in htm.core (you should check that `-- FORCE_BOOST          = OFF`)

Hope this helps. 

Or is the problem that non-boost application would be breaking because htm.core (with c++11) includes boost? That would be a bug!

**Comment by Thanh-Binh** [comment]
@breznak your idea does not work with gcc 8.3 for my non-boost applications.
htm.core is succesfully compiled with NEEDS_BOOST=0, FORCE_BOOST=0, but my app want to link to BOOST.
Maybe a bug here!

**Comment by breznak** [comment]
>  but my app want to link to BOOST.

htm.core does not provide/expose boost. So if your app requires boost (is that correct?), then you need to make sure the boost is provided to the custom app. 

> for my non-boost applications.

ok, I don't understand how that could happen. Can you make a trivial test-case where non-boost application does not link with htm.core, please? Including everything: source, cmake file

**Comment by dkeeney** [comment]
>  NEEDS_BOOST=0, FORCE_BOOST=0

Just for clarification, FORCE_BOOST=ON will tell the CMake script to override its computation and download (and use) boost.  NEEDS_BOOST is an internal variable.  If FORCE_BOOST is true OR the selected compiler does not support std::filesystem it will set NEEDS_BOOST to true and will download and build the std::filesystem module only along with the includes for boost.  But this is only to build the library.  

If your app needs boost includes or modules, you will have to provide them separately.

@Thanh-Binh you say your app does not use boost.  However the error you are getting seems to indicate that it wants `error_category` from boost.    
Perhaps you are using http_listener.h? see https://github.com/Microsoft/cpprestsdk/issues/637
If not, there could be other include files that indirectly reference something in boost.

**Comment by Thanh-Binh** [comment]
@breznak @dkeeney 
following your recommendation I finally find out the problem.
I forgot to set my compiler option **--std=c++17** for compiling my application!!!!
Best thanks for your help.

**Comment by breznak** [comment]
> I forgot to set my compiler option --std=c++17 for compiling my application!!!!

glad it works for you! :+1: 

To understand if there is a problem with htm.core, your non-boost app fails to link if htm.core internally uses boost (ie c++11)? 
@dkeeney (how) is that possible?

**Comment by Thanh-Binh** [comment]
@breznak : in ImportFileSystem.hpp, you use
#if __cplusplus >= 201703L
for deciding if Boost is used. I find this solution not so good.
Any improve?

**Comment by breznak** [comment]
> for deciding if Boost is used. I find this solution not so good.
Any improve?

what is a problem with that, and what would you propose?

**Comment by breznak** [comment]
> #if __cplusplus >= 201703L

c++17 is a requirement for `std::filesystem` (+other things like libc support) which we prefer to use instead of `boost:::filesystem`. 

> To understand if there is a problem with htm.core, your non-boost app fails to link if htm.core internally uses boost (ie c++11)?

I still don't understand why would your app break whether htm.core uses internally boost/not.
