### ISSUE TITLE
Avoid unfixed dependencies on git "master", use deterministic SHA/tag

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#590]
- ideally, use a Release for our dependencies
  - if not available/not usable (ie we need a newer fix), use a specific tag/commit-hash, in order to avoid silent breakages when upstream pushes a breaking commit, without us noticing! 

unfixed deps: 
- [ ] libYaml.cmake
- [ ] mnist_data.cmake

This is how to download a specific commit SHA from Github instead of master: 
`set(URL https://github.com/kerukuro/digestpp/archive/36fa6ca2b85808bd171b13b65a345130dbe1d774.zip)`

**Comment by breznak** [comment]
@dkeeney would you like to take this,please, once you have time?

**Comment by breznak** [comment]
Master for Windows recently became silently failing without us knowingly force-pushing anything broken! 

I am suspecting it is this issue, ie some of the deps using directly `master` silently updated.

**Comment by breznak** [comment]
@dkeeney this is how you download a specific commit SHA instead of master from github, 

`set(URL https://github.com/kerukuro/digestpp/archive/36fa6ca2b85808bd171b13b65a345130dbe1d774.zip)`

**Comment by dkeeney** [comment]
Ah, ok, we should change all of our downloads from master.  I did not know we could do that.

**Comment by breznak** [comment]
> we should change all of our downloads from master

done in #727
