### ISSUE TITLE
Points to clarify in README

### ISSUE THREAD

**Issue by david-pfx** [htm-community/htm.core#596]
Building for python on Windows 10

1. VS 2015 nearly builds, but breaks with 'file not found' right after downloading boost.
1. On 64-bit Windows (the usual nowadays) 32-bit python will not work
2. VS 2019 includes 64-bit python 3 (if enabled on install), and this works just fine if on the PATH.
1. VS 2019 build appears to use MSBuild, so maybe no need for CMake?
1. The sample `htm.examples.hotgym` has a dependency on matplotlib for its graphical display.

Well done guys. It takes a while, but with patience it builds and runs just fine.

**Comment by breznak** [comment]
Thanks for testing and the writeup! 

> VS 2015 nearly builds, but breaks with 'file not found' right after downloading boost.

so did you get this running? afaik only VS2017,2019 are supported (for python3,pybind11, ...requirements) 

> On 64-bit Windows (the usual nowadays) 32-bit python will not work

known, intended. #586 would be more explicit about that

**Comment by dkeeney** [comment]
> VS 2019 build appears to use MSBuild, so maybe no need for CMake?

MSBuild can be used if you want to manually build everything.  As a shortcut you can use startupMSVC.bat to create and configure htm_core.sln and then start up Visual Studio.   I used CMake to automate not only the build but also the install and deployment.  All of this could have been done entirely with MSBuild but the same CMake script also works for Linux and OS-x.

**Comment by david-pfx** [comment]
Thanks for the quick response(s). These are just from my notes, in case someone thought they were worth adding to the README. Do with them as you wish.
No, didn't quite get VS 2015 working. I think it would with a little work, but probably not worth the effort.
Yes, after a bit more reading about CMake I get it. Looks like it's also in VS 2019 now. Might be worth a note of explanation, 'cos many Windows devs will not be familiar with it.

**Comment by breznak** [comment]
Thanks for the review and note, @david-pfx . I'm going to close the issue, as from your points, 3. is the only supported setup (and that works). Please reopen if you want to extend/improve the Installation on Windows README section.
