### ISSUE TITLE
OSX Circle CI: switch to latest XCode 11 (beta) images. Use c++17

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#599]
XCode 11 is now avail on CircleCI, that would finally allow us to use c++17 with filesystem. 
- [ ] switch to XCode 11
- [ ] test working c++17 in CircleCI
- [ ] fully switch repo to c++17 (drop c++11) 
- [ ] possible related cleanups (rm boost?, ...) 

Related #55

**Comment by breznak** [comment]
Blocked by #612

**Comment by breznak** [comment]
@dkeeney @ctrl-z-9000-times what do you think about fully adopting c++17? 
- [ ] It would allow us to drop some support code/dependencies, as std::filesystem / boost
- [ ] make the parallelization #214 easy to try out.

**Comment by dkeeney** [comment]
Well, I don't know.  There may still be people out there still using C++11 for some reason.  Perhaps a candidate for a question to the general forum?

**Comment by breznak** [comment]
> here may still be people out there still using C++11 for some reason. 

fair point, I would prefer more modern c++ to unify the codebase (=no hacks for c++11/17 differences). On the other hand, code in c++11 would still run on c++17. 
Once we have binary releases, consumer-users & python-only users do not have to care, and for c++ devs I guess installing an up-to date compiler is not a problem. 

An option would be to leave this transition be, untill it is required by some thing like c++ Parallel TS, which so far failed to perform in my initial experiments.

**Comment by dkeeney** [comment]
> An option would be to leave this transition be, until it is required...

This is a hard call.  
- If we leave it as-is then we will have to rework our CI again later.
- If we do it now we might cause a problem with people trying to build with older software.  Something like where corporate management has dictated that all compilers remain at x until IT is ready to migrate everyone. (I have seen such situations).

My inclination is to leave it as-is and we drop C++11 and C++14 support and go to C++17 at the same point that we drop Python 2.7.    Maybe Jan 2020?

I don't know.  I will go with the majority opinion.

**Comment by breznak** [comment]
>  leave it as-is then we will have to rework our CI again later.

- shouldn't be too hard work, we'll just need to install a decently modern compiler in the CI (all but OSX already are c++17 conformant) 

> leave it as-is and we drop C++11 and C++14 support and go to C++17 at the same point that we drop Python 2.7. Maybe Jan 2020

that sounds reasonable, might even keep c++11 longer, until it is required.
