### ISSUE TITLE
Python encoders serialization

### ISSUE THREAD

**Issue by Leonardbcm** [htm-community/htm.core#600]
Hi everybody. I recently get this package working and I am using the python3 bindings.
Nevertheless, I have encountered some problems while trying to serialize encoders and encoder parameters.

Here is the code sample I have done : 

```
In [95]: params = RDSE_Parameters()

In [96]: params.size = 100

In [97]: params.sparsity = 0.1

In [98]: params.resolution = 0.1

In [99]: rdse = RDSE(params)

In [100]: with open("save", "wb") as f:
     ...:     pickle.dump(params, f)
     ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-100-6147ac3148f8> in <module>
      1 with open("save", "wb") as f:
----> 2     pickle.dump(params, f)
      3

TypeError: can't pickle htm.bindings.encoders.RDSE_Parameters objects

In [101]: with open("save", "wb") as f:
     ...:     pickle.dump(rdse, f)
     ...:
     ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-101-d8cd9ca6b44e> in <module>
      1 with open("save", "wb") as f:
----> 2     pickle.dump(rdse, f)
      3
      4

TypeError: can't pickle htm.bindings.encoders.RDSE objects
```

which is just creating a RDSE_parameters() object and then a RDSE() object, and trying to serialize them with pickle. This apparently does not work, although serialization works fine for spatial poolers and temporal memories. 
My question is then : will the pickle serialization of the encoders be available soon? Otherwise, what are the alternatives for serializing the rdse and rdse_parameters objects?

Thank you by advance for you answers. 

here is another sample of code where I try to serialize a date encoder. Since the date encoder is just an implementation of a rdse encoder, I run into the same error : 

```
In [102]: from htm.encoders.date import DateEncoder

In [103]: date_enc = DateEncoder(season=10)

In [104]: with open("save", "wb") as f:
     ...:     pickle.dump(date_enc, f)
     ...:
     ...:
     ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-13d5f28aa5c5> in <module>
      1 with open("save", "wb") as f:
----> 2     pickle.dump(date_enc, f)
      3
      4
      5

TypeError: can't pickle htm.bindings.encoders.ScalarEncoder objects
```

**Comment by breznak** [comment]
hi, 

> My question is then : will the pickle serialization of the encoders be available soon? 

probably not, see #160 

> Otherwise, what are the alternatives for serializing the rdse and rdse_parameters objects?

definitely, we use language-agnostic "API for serialization" from `Serializable.hpp`, (see there for `save/load()` and `saveFromFile,loadFromFile()` methods). 

That API you should use for serializing all our c++ and py (bindings) classes. 

Btw, when looking for examples or help how to do something, it's good place to check the `tests`, for example here it'd be: 
`bindings/py/tests/encoders/rdse_test.py`

PS: while you're at it, this would be a nice contribution: adding the serialization test to the RDSE py tests.

**Comment by Leonardbcm** [comment]
Thanks for you answer, I will have a look on the PR and Serializable.cpp. 

> PS: while you're at it, this would be a nice contribution: adding the serialization test to the RDSE py tests.

I will see what I can do, my current solution was to avoid pickle and to store the dictionary of parameters that where used for the instanciation of the RDSE object. It's obviously not as good as pickle.

**Comment by Leonardbcm** [comment]
I am now a little bit confused. I have looked at the test files and found a use of the Serialization interface in network_test.py. However, while trying to duplicate it on a RDSE_Params or RDSE object, I get this following error message: 

`AttributeError: 'htm.bindings.encoders.RDSE' object has no attribute 'saveToFile'`

I have then inspected the Serializable.hpp header file in which the Serialization interface is described for more information. 

In the requirements, thise first line tells : 

`1) subclass it from Serializable (This class).`

However, while the Network class has (in src/htm/engine/Network.hpp):
`class Network : public Serializable`,
the  RandomDistributedScalarEncoder (from src/htm/encoder/RandomDistributedScalarEncoder.hpp) does not seem to sublass Serializable:

`class RandomDistributedScalarEncoder : public BaseEncoder<Real64>`

I might be wrong due to my absence of knowledge in C++, but my guess is that the RDSE_Parameters and RDSE classes should subclass Serializable. Has someone successfully Serialized a RDSE or RDSE_parameter object yet? 

Thanks for your answers.

**Comment by breznak** [comment]
> the RandomDistributedScalarEncoder (from src/htm/encoder/RandomDistributedScalarEncoder.hpp) does not seem to sublass Serializable:

it does, BaseEncoder already requires Serializable, hence all our c++ encoders support it. 
```
class BaseEncoder : public Serializable
```

> Has someone successfully Serialized a RDSE or RDSE_parameter object yet?

as always, first look at the tests for examples: 
```
TEST(RDSE, testSerialize) {
```

**Comment by Leonardbcm** [comment]
> class BaseEncoder : public Serializable

Thanks for that I did not noticed it.

> TEST(RDSE, testSerialize) {

I meant in python. In the python test file for network (network_test) the serialization test is skipped : 
`@pytest.mark.skip(reason="pickle support needs work...another PR")`

and the other test files seems not to use the methods "save" or "saveToFile".

**Comment by breznak** [comment]
> I meant in python. 

yes, picke is skipped/unavailable, 

> and the other test files seems not to use the methods "save" or "saveToFile".

that's what I've been thinking saying it should be added. 

But looking at it: 
`bindings/py/cpp_src/bindings/encoders/py_RDSE.cpp` the py RDSE does not expose the c++ save/load methods. 

So currently serialization is not available for the encoder, as you mentioned, the encoder is basically state-less, so one can just store its parameters. 

The way forward would be to expose the c++ Serializable functionality in python. It should not be too hard, see SP for inspiration: 
`bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp`

I will help you review a PR if you want to do it.

**Comment by Leonardbcm** [comment]
> The way forward would be to expose the c++ Serializable functionality in python. It should not be too hard, see SP for inspiration:
> `bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp`
> 
> I will help you review a PR if you want to do it.

I would be happy to contribute on this repository and this would solve my problem, allowing me to store my python objects. 
However, I literally never coded anything in C++ so I don't think I can make it this easy.
