### ISSUE TITLE
yaml-cpp download failing

### ISSUE THREAD

**Issue by ljulliar** [htm-community/htm.core#607]
I'm trying to compile htm.core. I followed the instructions in the README and the build stops right after starting with the following error:

```
-- Obtaining yaml-cpp from https://github.com/jbeder/yaml-cpp/archive/master.zip
make[2]: *** No rule to make target 'yaml-cpp-download-prefix/src/yaml-cpp-download-stamp/yaml-cpp-download-skip-update', needed by 'yaml-cpp-download-prefix/src/yaml-cpp-download-stamp/yaml-cpp-download-configure'.  Stop.
make[1]: *** [CMakeFiles/yaml-cpp-download.dir/all] Error 2
make: *** [all] Error 2
CMake Error at DownloadProject/DownloadProject.cmake:179 (message):
  Build step for yaml-cpp failed: 2
Call Stack (most recent call first):
  YamlCppLib.cmake:30 (download_project)
  CMakeLists.txt:84 (include)
```
I'm using python 3.5.3 and CMake 2.7.3
Any idea of what could go wrong ?

Thank you!

**Comment by breznak** [comment]
hi, thanks for testing htm.core! 

> -- Obtaining yaml-cpp from https://github.com/jbeder/yaml-cpp/archive/master.zip

this seems like a networking err on your end. Verify the connectivity, alternatively you can manually download the yaml-cpp/master.zip and provide that. Find details in the README

**Comment by ljulliar** [comment]
Network access is working just fine. So in the meantime I did download the 3rd party files by hand in the proper directory. Now I'm having a different error:

```
-- /home/ljulliard/misc/applications/Numenta/htm.core/build/ThirdParty/share/yaml-cpp.zip
-- Obtaining yaml-cpp from /home/ljulliard/misc/applications/Numenta/htm.core/build/ThirdParty/share/yaml-cpp.zip
make[2]: *** No rule to make target 'yaml-cpp-download-prefix/src/yaml-cpp-download-stamp/yaml-cpp-download-skip-update', needed by 'yaml-cpp-download-prefix/src/yaml-cpp-download-stamp/yaml-cpp-download-configure'.  Stop.
make[1]: *** [CMakeFiles/yaml-cpp-download.dir/all] Error 2
make: *** [all] Error 2
CMake Error at DownloadProject/DownloadProject.cmake:179 (message):
  Build step for yaml-cpp failed: 2
Call Stack (most recent call first):
  YamlCppLib.cmake:30 (download_project)
  CMakeLists.txt:84 (include)
```
And just for the record

```
$ ls -l /home/ljulliard/misc/applications/Numenta/htm.core/build/ThirdParty/share/
total 18132
-rw-r--r-- 1 ljulliard ljulliard  1757116 Aug  5 13:22 boost.tar.gz
-rw-r--r-- 1 ljulliard ljulliard   335759 Aug  5 13:27 cereal.tar.gz
-rw-r--r-- 1 ljulliard ljulliard  1665168 Aug  5 00:43 eigen.tar.bz2
-rw-r--r-- 1 ljulliard ljulliard   992298 Aug  5 13:25 googletest.tar.gz
-rw-r--r-- 1 ljulliard ljulliard 11501865 Aug  5 13:26 mnist.zip
-rw-r--r-- 1 ljulliard ljulliard   548404 Aug  5 13:26 pybind11.tar.gz
-rw-r--r-- 1 ljulliard ljulliard  1757116 Aug  5 13:22 yaml-cpp.zip
```

**Comment by breznak** [comment]
> Network access is working just fine.

i'm sorry for your inconvenience setting this up. But I've just rebuilt the whole repo and wasn't able replicate your problem. So it likely is something (temporarily) with your side. 

> did download the 3rd party files by hand [..] having a different error:

I haven't really tried the air-gapped method myself yet. I'll CC @dkeeney if he wants to look into once he's back. 

In the meanwhile, I'd suggest to completely remove the build/ folder and retry the install.

**Comment by ljulliar** [comment]
I upgraded to cmake 3.15.1 and it solves the issue. Thank you again for your help.

**Comment by dkeeney** [comment]
> I'm using python 3.5.3 and CMake 2.7.3

I am surprised that the CMake scripts did not give you an error and say that the minimum requirement is CMake 3.3.

**Comment by ljulliar** [comment]
Another comment: I was trying to compile htm.core on my Debian 9 (Stretch) distro and it didn't work.  Debian 9 comes with gcc 6 and there are -W flags used in htm.core Makefile that requires gcc 7 or above.

I think it would be worth mentioning GCC 7+  as a prerequisiste in the README.md. Not that Debian 10 is fine as it comes with GCC 8.

**Comment by dkeeney** [comment]
>  I was trying to compile htm.core on my Debian 9 (Stretch) distro and it didn't work. 

Hmmm, that sounds like a bug.  gcc 6 is c++14.  We should handle -std=c++11 and above although  c++11 and c++14 it will have to download and build the boost filesystem module as part of the dependency build which takes a long time.

Can you give me more details about what did not work?

**Comment by ljulliar** [comment]
Sorry I meant Cmake 3.7  not 2.7. And sure enough 3.7 didn't work but I
can't remember seeing an error message telling me it has to be 3.3+

As for gcc 6 the error was on the  following lines that the compiler was
rejecting:

#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"

Sorry I can't give you the exact error message because I upgraded to gcc 8
in the meantime.

Hope this helps nonetheless

**Comment by dkeeney** [comment]
> -Wimplicit-fallthrough

Ah, good catch.  That was added in GCC7.  We need to not include that if the compiler is GCC6.

**Comment by dkeeney** [comment]
I think everyone is happy with this fix.  So we can close it.
