### ISSUE TITLE
Generic Encoder Region

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#637]
This is a new topic to discuss how to implement a Generic Encoder Region.

**Comment by dkeeney** [comment]
A Generic encoder region would be ideal.  There are a couple of problems I am struggling with:
- The arguments to each encoder are different.  I think this is doable but it complicates things a bit.
- I would like to dynamically allocate an encoder based on the name of the encoder passed in as an argument.  I would like to be able to allow someone to create a custom encoder and register it with this Generic encoder Region....without messing up the plugin boundaries.

**Comment by dkeeney** [comment]
**Arguments**
The arguments problem has always been a complication with regions.
 The region starts with a set of argument descriptors in the Spec.  This describes the name, type, access, and default value of each argument.  The yaml string passed into the Region creation is merged with the values in the Spec to produce the set of arguments that are to be passed to the algorithm.

Somehow I need to:
- Assign the value to a variable with that name so that it can be passed into the algorithm at creation.
- Be able to return the variable by name if one of the getParameterxxx( ) functions are called.
- Be able to set the variable by name if one of the setParameterxxx( ) functions are called and it has ReadWrite access permissions. (the encoders all seem to be CreateAccess so they cannot be changed once the encoder is allocated).

All current regions have done this by laboriously encoding each set of arguments for algorithm allocation, each serialization,  and each get/set function.  So, the challenge is to find a way to do this generically.   i.e.  given name, value, and type, assign this to a variable in a structure without hand coding it. 

This needs to be done in such a way that the spec can still be used in either C++ or Python.

**Comment by dkeeney** [comment]
Back in my old C coding days it was no problem.  
- All you need is the variable's offset into a structure and then using pointers and casts for type, plop the variable's value into the structure at that offset.  These offsets can be obtained using a macro that defines the fields in the structure.
- If a structure had no padding and the field descriptors in the Spec were in the same order as the variables in the structure used to hold the parameters then we could calculate the offset based on data type size.
- It could also be done with an array of pointers to where the variables are located.  The pointer array would need to be indexed by the variable name.  But someplace there still needs to be something to get the pointers.
- If the variables were all the same type then it becomes an array and all we need is the index for the variable by name, perhaps just the order in the descriptor.

In the C++ world I could get these to work but none of these would be considered 'appropriate'.
But somehow we still need a name indexed mapping of an argument's descriptor to its variable.

What we really need is introspection so we could determine the layout of a structure at runtime. I read someplace that this was being considered in C++.  I will go do some research.

**Comment by dkeeney** [comment]
After reading up on introspection it looks like it is not likely to exist in C++ before C++20.
It is amazing the lengths people have gone to in order to get introspection types of functions.
We don't really need it to that extent. All we need are the descriptions of the fields of the parameter structure.  

**So, here is a proposal:**

Place the following in htm/encoders/BaseEncoder.hpp
```

typedef struct {
  std::string name;
  int offset;
  std::string type;
} ParameterDescriptor;

#define FIELD(n)                   \
  { name, {                        \
    #n,                            \
    (int)(&args_-> n - &args_),    \
    typeid(s ##  ::##n).name       \
  }}

```

Place the following public members in the body of each encoder class:
```
std::string getName() { return "RDSE";}
std::map<std::string, ParameterDescriptor> descriptor = {
    FIELD(size), 
    FIELD(activeBits),
    FIELD(sparsity), 
    FIELD(radius),
    FIELD(resolution),
    FIELD(category),
    FIELD(seed)
};
```
Of course, each encoder body will have different set of lines in this map to correspond with its parameters.  Effectively what I have done is move the mapping of fields down into the encoder.
But with this I think I can construct a single generic encoder Region class that can accept an Encoder class being plugged in without prior references at compile time. All the EncoderRegion class would need is the class name like we do the other region plugins.  I would have to write a generic encoder interface that would allow .py implemented encoders to be registered as well.

**restrictions**
- Encoder must have a default constructor and an initialize( ) function because I will have to construct it prior to having the parameters.
- I might also be able to automatically construct the Cereal serialization generically with this as well (placed in the BaseEncoder class) as long as the encoder class does not contain state other than the parameters.
- Parameter types must correspond to simple types as defined in NTA_BasicType

What do you think?

**Comment by dkeeney** [comment]
Correction: macro looks like:
```
#define FIELD(n) { #n, { #n, (int)(&args.n - &args_), typeid(args_. ## n).name } }
```

**Comment by dkeeney** [comment]
Sorry this topic is getting so long...

As I start to build this EncoderRegion class and I am having a problem with BaseEncoder.
I need a pointer to a generic  encoder class, regardless of the encoder; to be used in my factory. Normally this would be a pointer to the BaseEncoder class.  However, the BaseEncoder class is templated so all references to the BaseEncoder class must include the input type but that can be different between encoders.  A generic Encoder Region cannot be built without the BaseEncoder being polymorphic.

Not sure how to handle this.

My current thinking is to remove the template from the BaseEncoder class and add a set of oveerloaded encoder( ) functions, one for each input type that it might want.   Then I will have to ask the encoder what it wants for an input type and then do a switch on that to pick the right encode(input, output) function.  I don't really like this but I am out of ideas.

Ideally, the EncoderRegion class should work only with the BaseEncoder class using inheritance. Templates don't work with inheritance.

**Comment by breznak** [comment]
> The arguments to each encoder are different.

a simplest solution I had in mind is the user would pass an instance of the encoder (means the params are dealt with) to the EncRegion. 

How many encoders do we have now, RDSE & Scalar? We could unify their params. 

What I thought this could work with is JSON-params as constructor argument, so you could call `EncoderRegion( "RDSE", "{JSON params: for rdse}") `

> My current thinking is to remove the template from the BaseEncoder class 

Can't the Region be templated as well, and pass it to the BaseEncoder? 

Or..if this is getting overcomplicated, let's go with just a single-encoder region (RDSE) as you've originaly started. 

Sorry, I'm travelling, will read properly rest of the thread by the next week

**Comment by dkeeney** [comment]
Enjoy your trip and we can discuss this more when you return.

I am beginning to think that the real problem designing a generic region is figuring out how to pass arbitrary input data to the encoder.  For the parameters the Region does use JSON but the data to be encoded for each cycle is the problem. The `input` in the call to `encode(input, output)`.   Each encoder could be expecting a different type and where will this data come from?  A stream?  A file? A callback to the application? Perhaps a NetworkAPI Input that has a link to an upstream region like VectorFileSensor.  Maybe all of the above.

Lots to think about.

**Comment by breznak** [comment]
> The input in the call to encode(input, output). Each encoder could be expecting a different type and where will this data come from? A stream? A file? A callback to the application?

true, feeding in the date is more of a problem. So should this be part of the VectorFileSensor, and just make it more generic to choose arbitrary encoder..?

**Comment by dkeeney** [comment]
I don't think so.   The VectorFileSensor does not output an SDR.  It outputs an array of data (like one record) for each cycle.  At the moment its output is an Array object containing an array of Real32 but with a little magic we could make that any of our types.  The Link can pass any of the data types in the Array object and the values do not have to be just 1.0 and 0.0.

We could pipe that into our EncoderRegion with a Link.  

So by using the VectorFileSensor and maybe some new regions that obtain data from other places like streams or web servers we can solve the problem of where the data comes form.   Now we just need to get it into the encoder(input, output) function in such a way that the target encoder gets it in the type it expects.

**Comment by breznak** [comment]
It seems the generic encode region is not feasible, closing as Wontfix. Please reopen if you think otherwise.
