### ISSUE TITLE
Python bindings Region.getOutputArray() always returns an empty array

### ISSUE THREAD

**Issue by fcr** [htm-community/htm.core#651]
As part of my Python3  port of selected htm research code, I need to access the output data of the regions defined in Python.
In the binding code, py_Engine.cpp Region.getOutputArray() just returns an empty array.

Without a functional getOutputArray(), there doesn't seem to be a way to access the output of a region from Python.

**Comment by dkeeney** [comment]
Hmmm, that should give you a numpy array.
I cannot look into it until next week but I will definitely check this out.
Thanks for reporting it.

**Comment by fcr** [comment]
C++ is not my comfort zone otherwise I would have tried to fix it myself.
I am stuck until this is working. :-(

**Comment by breznak** [comment]
@fcr could you post a snip of a test-case, so I can add it to the API tests? And thanks for reporting!

**Comment by fcr** [comment]
[@breznak ](https://github.com/breznak) I have extended the bindings network_tests to test the getInputArray() and getOutputArray(), since both are currently not working. As a bonus this tests whether the network is indeed transferring the data between regions.
[network_test.py.zip](https://github.com/htm-community/htm.core/files/3563344/network_test.py.zip)

**Comment by dkeeney** [comment]
I will not have access to a computer until tomorrow but I remember now that
this accepts and returns a python array object rather than a numpy array.
GetParameterArray() requires the array to exist before calling and it will
get populated during the call.

See bindings/py/cpp_src/bindings/engine/py_Engine.cpp lime 90.

I do not know what the original API did.

**Comment by fcr** [comment]
What you describe is correct for getParameterArray but not getOutputArray (nor getInputArray).
This is the current implementation in py_Engine.cpp:

        py_Region.def("getOutputArray", [](const Region& self, const std::string& name)
        {
            auto array_ref = self.getOutputData(name);

            return py::array_t<htm::Byte>();
        });

**Comment by dkeeney** [comment]
Ok, now that I am back at a computer I can see what you are asking for.

The bindings for getOutputArray() and getInputArray() are not right.  These should be giving access to the input and output buffers (or a copy of them).

The original nupic API documentation did not mention these functions.
http://nupic.docs.numenta.org/stable/api/network/regions.html
But obviously they are needed and in fact they are used in some of the Nupic guides.

In C++ these functions return a const reference to an Array object.   This Array object is a container for an array of any numeric data type or an SDR object (which most Regions are now using).  From the Array object you can get the SDR object and from that you can get either a sparse Integer array of indexes or a dense byte array. The Array object is basically a stand-in for a numpy array in Nupic.  But Nupic does not have an SDR object so we need to expand the API a little to accommodate it.

Both the SDR and the Array C++ objects are now exposed to python in the bindings.  So I think we will need a two step process to get the values returned by getOutputArray( ) and getInputArray( ) into a numpy array.  The first step returns the Array object as a py_Array_t object which is a subclass of a python array object.  The second step is to obtain a numpy array from the Array object as a dense array.  OR obtain an SDR object from the Array object and then from that get either a dense array or a sparse array.

So I am proposing something like this:
```
    a = sp.getOutputArray('bottomUpOut")
    element = a[index]          # I think I can do this directly on the Array object
    b_dense = np.array(a)     # This turns it into a dense numpy array

    # This extracts the sparse index array IF this happens to contain an SDR type in the Array object.
    if a.isSDR():
        c_sparse = a.getSDR().getSparse()    
```

@fcr  If this looks like a reasonable plan to you I can play around with this and see what I can get to work.  Oh, and thinks for the unit tests.  I will start with that.

**Comment by dkeeney** [comment]
As a side note, there seems to be several other Region function calls related to dimensions on Input and Output buffers that did not have bindings.  I will add some of those as well.
```
            .def("getInputDimensions", &Region::getInputDimensions)
            .def("getOutputDimensions", &Region::getOutputDimensions)
            .def("setInputDimensions", &Region::setInputDimensions)
            .def("setOutputDimensions", &Region::setOutputDimensions)
            .def("getInputElementCount", &Region::getNodeInputElementCount)
            .def("askImplForOutputDimensions", &Region::askImplForOutputDimensions)
            .def("askImplForInputDimensions", &Region::askImplForInputDimensions);
```

**Comment by dkeeney** [comment]
Am I missing something or were NONE of the python implemented regions in the nupic repository ported to Python3 in nupic.core?

I am looking in the py folder in htm.core and I don't find any in there.  The reason I asked is that as I started to use the unit tests network_test.py I discovered that none of the tests actually tested calling the compute() on a python implemented region implementation.   There is one in network_test.py, the LinkRegion class,  but it did not implement the compute( ) function.   The rest of the tests in this module just check configuration things.

I guess I was under the unfounded assumption that we had the facility to use regions that were implemented in python or C++ and that we had unit tests to prove that it was working.  But we don't.

So this may end up being more work than I thought.

**Comment by fcr** [comment]
getInputDimensions and getOutputDimensions are normally implemented by the Region subclass as you can see in the unit tests I sent you earlier.

I have Python regions working but just cannot get the output data from them.
I had to add  .def("executeCommand", &Region::executeCommand) and some other minor additions to the Python bindings but have not made a push request for this yet.
I have attached a simple Python region as an example of a working Python region. BTW my port of the ColumnPooler using your Connections implementation runs twice as fast as the original ColumnPooler in htmresearch.
[RawSensor.py.zip](https://github.com/htm-community/htm.core/files/3567731/RawSensor.py.zip)

**Comment by breznak** [comment]
> were NONE of the python implemented regions in the nupic repository ported to Python3 in nupic.core

In numenta's nupic.core, there's nothing for py3, our community nupic (nupic.py) is almost all ported to python3, so if there are py regions of interest, it's the place to grab them from. 
Of your htm.core, what was in nupic.core, is here, we didn't port anything from nupic to here (we could) 

> So this may end up being more work than I thought.
>  had to add .def("executeCommand", &Region::executeCommand) and some other minor additions to the Python bindings but have not made a push request for this yet.

I'd suggest to fix first what's blocking @fcr , and later keep adding additional py compatibility/regions. 

> ColumnPooler using your Connections implementation runs twice as fast as the original ColumnPooler in htmresearch.

cool to hear, thanks! :horse_racing: 

> my port of the ColumnPooler using your Connections 

Fred, can you later give us some wrapup on what's ported, how stable/volatile it is etc? I'd like to have the more or less stabilised parts merged in this repo (ie CP)

**Comment by fcr** [comment]
As I wrote earlier I am porting all the pieces of htmresearch that implement the location_network which BTW includes the ColumnPoolerRegion, GridCellLocationRegion, the RawSensor region and the RawValues - all very useful regions in their own right.

I am nearly there. 

How about I just submit a push request with the whole shabang with unit tests once I see that it is stable (with a wrapup, of course)?

**Comment by dkeeney** [comment]
> (nupic.py) is almost all ported to python3

Oh, I thought we were going to put the python3 code in htm.core.
So, Ok I know where to look now.

> How about I just submit a push request with the whole shabang

Sure.  It does not all have to work before you push.  But that would give me something to code against.  Thanks.

**Comment by fcr** [comment]
Just give me the missing piece first :-) - getInput/OutputArray()

**Comment by dkeeney** [comment]
> Just give me the missing piece first :-) 

Sure.  It is easy to go down a rabbit hole and forget the original objective.

**Comment by dkeeney** [comment]
My fix is in PR #655.  This adds the getOutputArray() and getInputArray() as requested.

As I was constructing the unit tests for this it became apparent that there was no way to directly populate an input buffer from python.  Normally there is some sort of encoder that does this.  But for testing it would be useful to force an array of data into an input buffer so I added the function setInputArray().

Now, there are some conditions associated with these functions.
- None of these functions can be used until after initialization().  That is because the buffers are not created until then.
- TMRegion has a set of 5 outputs, None of these are generated unless there is an Outgoing link attached (or you are in debug mode).  As a result, getOutputArray( ) is normally not going to get anything if that output is not attached to a link.  So for the unit test "testBuiltInRegions" in "network_test.py" I turned on debug mode.

During this exercise I discovered that most of the NetworkAPI related test on the .py side were either disabled or did not really test much.  So for future PRs I need to be more diligent about adding more .py tests.

**Comment by dkeeney** [comment]
Another discovery was that, unlike C++ region implementations, Python region implementations do not have access to it's corresponding Region object.  This means that within the region implementation it cannot access the input or output buffers or dimensions except in the compute( ) function where the input and outputs are explicitly passed in.  That means that it cannot do buffer related things in the constructor or initialization.  This is not a problem so far but eventually we might have to pass the reference to the Region in the constructor for the .py region implementations.

**Comment by fcr** [comment]
Thank you [@dkeeney](https://github.com/dkeeney). It works as advertised.
Now I can go ahead and get my code to work. :-)
