### ISSUE TITLE
no PredictiveCells found by TemporalMemory

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#654]
By testing TM for anomaly detection with a simple sinus wave data, I found the raw anomaly score is always 1. TM calculates the anomaly using predictive cells internally. 
If I check for predictive cells, then I found that no cell is predicted for very long time period. So that it explain me, why the raw anomaly scores are always 1.

I am wondering, why TM can not find any predictive cell?
Any idea? thanks

In my experiment, SDR has 128 bits and 4 active bits 
```
TM.initialize(std::vector<uint>{128}, 8,
      /*   activationThreshold         */ 13,
      /*   initialPermanence           */ 0.21,
      /*   connectedPermanence         */ 0.50,
      /*   minThreshold                */ 10,
      /*   maxNewSynapseCount          */ 20,
      /*   permanenceIncrement         */ 0.10,
      /*   permanenceDecrement         */ 0.10,
      /*   predictedSegmentDecrement   */ 0.0,
      /*   seed                        */ 42,
      /*   maxSegmentsPerCell          */ 255,
      /*   maxSynapsesPerSegment       */ 255,
      /*   checkInputs                 */ true,
      /*   externalPredictiveInputs    */ 0,
      /*   anomalyMode 		             */ TemporalMemory::ANMode::RAW);
```

**Comment by ctrl-z-9000-times** [comment]
4 active inputs is far too few active inputs.  The TM needs enough active mini-columns such that if a single cell per mini-column activates, that it has enough active cells to meet the activationThreshold, which is 13 in this scenario.  I ran this scenario with 20 active inputs and the anomaly significantly decreases.

```python
import htm.algorithms
tm = htm.algorithms.TemporalMemory([128], 8,
      activationThreshold         = 13,
      initialPermanence           = 0.21,
      connectedPermanence         = 0.50,
      minThreshold                = 10,
      maxNewSynapseCount          = 20,
      permanenceIncrement         = 0.10,
      permanenceDecrement         = 0.10,
      predictedSegmentDecrement   = 0.0,
      seed                        = 42,
      maxSegmentsPerCell          = 255,
      maxSynapsesPerSegment       = 255,
      checkInputs                 = True,
      externalPredictiveInputs    = 0,
      anomalyMode                 = htm.bindings.algorithms.RAW)

import htm.encoders.scalar_encoder
enc = htm.encoders.scalar_encoder.ScalarEncoderParameters()
enc.size = 128
enc.activeBits = 20
enc.minimum = -1
enc.maximum = 1
enc = htm.encoders.scalar_encoder.ScalarEncoder( enc )

from math import sin, pi
x = 0
while True:
 y = sin(x)
 x = x + (2*pi / 100)
 sdr = enc.encode( y )
 tm.compute( sdr )
 print(y, tm.anomaly )
```

HTH

**Comment by breznak** [comment]
> The TM needs enough active mini-columns such that if a single cell per mini-column activates, that it has enough active cells to meet the activationThreshold, which is 13 in this scenario.

Thanks Binh for reporting! 

this should part of the #536, is there some stable method we'd check for sensible settings in this case? We cannot require that always SP's active output count > activation threshold, but we could run some statistics and make the check for a long-term? The outcome would be to catch incorrect user's settings, as shown here. These problems are tricky, as there's no failure, just the network does not work (as expected).

**Comment by Thanh-Binh** [comment]
Thanks all for your Feedback.
Ít ít clear that works with more active bits.
But not clear for me that we go further outside the limit of 2% SDR. In your test even with 20%.
My question: what is happend when I use 2% active bits of larger sdr length?
Exactly, here n=1000 instead of 128
And w=20
What do you think?

**Comment by Thanh-Binh** [comment]
I think, my last question is only a parameter-tuning for specific tasks, so that I'd like to close it....
