### ISSUE TITLE
getPredictiveCells empty

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#658]
I want to retrieve what cells are predictive, but i am getting SDR with just zeros.

Can be replicated by hotgym python example, instead of calling 
```
tm.compute(activeColumns, learn=True)
```
call functions separately like following (must be called like this because in other points in program segments are not valid)
```
 tm.activateDendrites(True)
 predictiveCellsSDR = tm.getPredictiveCells()
 tm.activateCells(activeColumns,True)
```
and you will got predictiveCellsSDR with zeros all the time...

Any hints? Can i kindly ask maybe @breznak ? you were developing some of the TM code as i can see in file history

**Comment by breznak** [comment]
Thanks @Zbysekz for reporting! 

- This indeed seems like a bug in the py bindings (such construction works in c++). 
- it is a valid use-case to replace `tm.compute` with separate `tm.activateDendrites()` for reasons as you mention
- Could you create a PY unit test for this? 

I'll try, but maybe I'll get to this only at Wed.

**Comment by Zbysekz** [comment]
There is the python test... i was too hasty, it works correctly. For the hotgym it takes approx 28 steps before i get some prediction with default params and that is probably fine. Sorry for false alert :) But we can merge the test, it is simple but at least something.

**Comment by breznak** [comment]
>  Sorry for false alert :) But we can merge the test, it is simple but at least something.

this is the optimal resolution, the problem is gone/none, and I get the test :wink:
