### ISSUE TITLE
Build error due to Eigen warning on gcc 9 

### ISSUE THREAD

**Issue by marty1885** [htm-community/htm.core#684]
Hi, I'm building HTM.core on my Arch box using the python script and failed. 

```
git clone https://github.com/htm-community/htm.core
cd htm.core
python setup.py install --user --force
```

With the error message

```
/home/marty/Documents/not-my-projects/htm.core/build/ThirdParty/eigen/eigen-src/Eigen/src/Core/CwiseBinaryOp.h:105:49: error: implicitly-declared ‘constexpr Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1> >::ArrayWrapper(const Eigen::ArrayWrapper<Eigen::Matrix<int, -1, 1> >&)’ is deprecated [-Werror=deprecated-copy]
  105 |       : m_lhs(aLhs), m_rhs(aRhs), m_functor(func)
      |                                                 ^

```

Am I doing anything wrong? What can I do to fix this?

commit: HEAD
compiler: GCC 9.1.0
OS: Linux x64

**Comment by breznak** [comment]
> Am I doing anything wrong? What can I do to fix this? 

no, you're fine, I'll try to fix it tmr. 
It's that now we use Eigen, and that being header-only does not benefit the exception that we don't care for warnings in 3rd party dependencies. So it triggers a warning on newer gcc, which triggers the error. 

I'll have a look if there's a newer release for eigen possibly fixing that. 

Thanks for reporting and sorry for the inconvenience!

**Comment by breznak** [comment]
So Eigen 3.3.7 (from Dec/2018) is the latest release, I can confirm this also on gcc-9.1 on ubuntu.
