### ISSUE TITLE
How to get distal connections

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#695]
Hello, can i ask for help about getting "distal" connections from TM? It is for the visualisation tool that i am working on. I have hard time to understanding encapsulation in src/htm/algorithms/Connections.cpp

To be able to do this:
![image](https://user-images.githubusercontent.com/23330229/65767596-966d4700-e12e-11e9-9b04-3893ae82dff0.png)

What i basically need is to get from python temporal memory object this data:
for one specific cell, return all connected (either active or potential) cell indexes.

Any toughts?
I can create necessary method (if missing) also in C++ but little guidance can spare me some effort.

**Comment by Zbysekz** [comment]
Maybe i can use 
`segmentsForCell(const CellIdx cell)`
and for each segment call `synapsesForSegment(const Segment segment)`
But then i need to call `dataForSynapse(const Synapse synapse)` to get data and then
get from synapseData the presynapticCell ? I am not sure...

**Comment by Zbysekz** [comment]
Any toughts @breznak @ctrl-z-9000-times ?

**Comment by ctrl-z-9000-times** [comment]
Yes, your approach is correct.  You need to get the `connections` object from within the TM and then query the `connections` object, first to find the segment you're looking for and then to find the synapse you're looking for.  Finally you will need to extract the permanence value from the `connections` object either using method `permanenceForSynapse` or using method `dataForSynapse`.

BTW: The C++ documentation  is good, but the python documentation is incomplete.  For methods which are implemented in both C++ & Python, the C++ documentation applies for both languages.

**Comment by breznak** [comment]
...and you might have a look at `py/htm.advanced.algorithms.connections` there's some additional functionality

**Comment by Zbysekz** [comment]
Wasn't so hard afterall :)

```
def getAllPresynapticCellsForCell(tm, cellID):
    segments = tm.connections.segmentsForCell(cellID)
                  
    synapses = []
    for seg in segments:
        for syn in tm.connections.synapsesForSegment(seg):
            synapses += [syn]
 
    presynapticCells = []
    for syn in synapses:
        presynapticCells += [tm.connections.presynapticCellForSynapse(syn)]
     
    return presynapticCells
```

I can probably include this code in `py/htm.advanced.algorithms.connections` when i got more code like this if you agree.

**Comment by breznak** [comment]
> I can probably include this code in py/htm.advanced.algorithms.connections

please do, this will be a useful method :+1: 
-  add some doc
- write if from connections' perspective
