### ISSUE TITLE
Concatenate() Method of SDR class

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#696]
Hi all, currently this method uses as input a vector of const SDR*
We use it as follows
vector<const SDR*> all;
For I=1:2
   SDR local({5});
   all.push_back(&local);

SDR c({10});
C.concatenate(all);
Unfortunately, it fails to run because the dimension of SDR after the for-loop is zero.

I really do not understand why did not you use a simple SDR instead of pointer, I.e. vector<const SDR>.
It works perfectly with vector<const SDR> .

Can you all ander my question? Thanks

**Comment by ctrl-z-9000-times** [comment]
SDR.Concatenate uses pointers because: Pushing data into the a `vector<SDR>` will copy the data, but using pointers avoids copying the data into the vector.

You say it fails?  Can provide a snippet of source code which demonstrates the failure, for debugging this issue?

**Comment by Thanh-Binh** [comment]
@ctrl-z-9000-times 
here is my source code:
```
  std::vector<const SDR*> allSDR;
  for (int i = 0; i < 3; ++i)
  {
    SDR A({10});
    A.randomize( 0.30f ); 
    allSDR.push_back(&A);
    for (auto e : A.getSparse())  std::cout << " ," << e;
    std::cout << std::endl;
  }
  SDR sdr({30});
  sdr.concatenate(allSDR);
  for (auto e : sdr.getSparse())  std::cout << " ," << e;
  std::cout << std::endl;
```

**Comment by ctrl-z-9000-times** [comment]
The problem with this code is that SDR `A` is allocated on the stack and so it dies at the end of the for loop.  SDR A is created and destroyed 3 times.  Then after the loop ends the memory on the stack which held `A` is repurposed to hold variable `sdr`.  Try using this code instead:
```
  std::vector<const SDR*> allSDR;
  for (int i = 0; i < 3; ++i)
  {
    auto A = new SDR({10});
    A->randomize( 0.30f ); 
    allSDR.push_back(A);
    std::cout << *A << std::endl;
  }
  SDR sdr({30});
  sdr.concatenate(allSDR);
  std::cout << sdr << std::endl;
```

**Comment by Thanh-Binh** [comment]
Thanks David for your explain!
