### ISSUE TITLE
Replace cmake dependency with cmake from pip 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#698]
So people basically need to install only python and compiler, and rest will be installed from `pip`. 
https://pypi.org/project/cmake/ 

- on the other hand, c++ developers/users only need `cmake, gcc` and don't need to install python (for bindings).

**Comment by dkeeney** [comment]
But if we provide a pre-built binary wheels, why do python users need CMake?  I thought the objective of pip installs was that it did not require building the package.

**Comment by breznak** [comment]
> But if we provide a pre-built binary wheels, why do python users need CMake? 

yes, I was talking about source-build users, you're right binary users who install through pip do not need any of the dependencies (except python)

**Comment by breznak** [comment]
Closing, cmake added to pip requirements.
