### ISSUE TITLE
Faster Windows builds on CI 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#700]
The windows CI build is the slowest from all the platforms (about 2-3x), which slows down the PR acceptance/check process. 

Here are some ideas for optimization: 
- [ ] build only in `Release` mode in CI 
  - we need the "both Release/Debug" mode for source-builds, developers. 
  - can we add a flag, or determine if `setup.py` is ran in CI, and then build only in Release mode? 
- [ ] use `/MT` (which should be alternative to `make -j4`) to speedup build itself
  - or use moder cmake #698 and pass `-j4` from there

**Comment by breznak** [comment]
CC @dkeeney this is a low priority, but would be nice to have. If you can look at that?

**Comment by dkeeney** [comment]
> use /MT (which should be alternative to make -j4) to speedup build itself 

/MT means the compiled program supports multi-threading.  /MD means mult-threaded shared library.     Has nothing to do with the number of threads used by the compiler.

We don't need both debug mode binaries for the CI.

**Comment by breznak** [comment]
> We don't need both debug mode binaries for the CI. 

I see about /MT, still, only "Release" for CI would cut the time in half :+1:
