### ISSUE TITLE
AttributeError of SP getOverlaps

### ISSUE THREAD

**Issue by be4pro** [htm-community/htm.core#712]
After installing htm.core from PyPI into my win7,
I ran `py -m htm.examples.sp.sp_tutorial` and get 

> AttributeError: 'htm.bindings.algorithms.SpatialPooler' object has no attribute 'getOverlaps'

Is something I was missing? I can run `py -m htm.examples.sp.hello_sp` OK.

**Comment by breznak** [comment]
Hi David, 

thanks for reporting! this is indeed a bug (which slipped through as the example is not run automated by the CI), the `getOverlaps()` has been replaced, now `compute()` returns that info. 

```
@return overlap
an int vector containing the overlap score for each column. The
overlap score for a column is defined as the number of synapses in
a "connected state" (connected synapses) that are connected to
input bits which are turned on.
Replaces: SP.calculateOverlaps_(), SP.getOverlaps()
*/
virtual const vector<SynapseIdx> compute(const SDR &input, const bool learn, SDR &active);
```

- [ ] the example should be fixed
- [ ] add getOverlaps removal to Changelog

**Comment by be4pro** [comment]
Hi breznak,

thanks for your reply. I'm new to programming and would like to make sure I understand it correctly. Does that mean I need to change codes in SpatialPooler.cpp and recompile a new algorithms.pyd to solve the issue? Given I don't know about coding cpp, what could I do?

Also, I got issues running hotgym example. I got this output while running `python -m htm.examples.hotgym`

> TypeError: infer(): incompatible function arguments. The following argument types are supported:
    1. (self: htm.bindings.algorithms.Predictor, pattern: htm.bindings.sdr.SDR) -> Dict[int, List[float]]
>
>Invoked with: <htm.bindings.algorithms.Predictor object at 0x0000000009D45070>, 0, <htm.bindings.sdr.SDR object at 0x000000000994A130> 

Does this mean besides installing htm.core package from pip, I need to install CMake, SDK or other C++ related tools to make it work? My intention is simply using htm.core in Python.

**Comment by breznak** [comment]
> Does that mean I need to change codes in SpatialPooler.cpp and recompile a new algorithms.pyd to solve the issue?

no, we'll make a simple fix to the examples for the bugs you've discovered. 

> Also, I got issues running hotgym example. 

looks like another deprecation change. I'll look into that, thanks. 

> Does this mean besides installing htm.core package from pip, I need to install CMake, SDK or other C++ [...]

no, that would not be the case,

**Comment by t0n8** [comment]
Just tried https://github.com/htm-community/htm.core/blob/79d88da1456c955b00325c7928a297c3ac294347/py/htm/examples/hotgym.py and was wondering if line 234 needs to be changed to 
             `np.arange(len(anomaly)), anomaly, 'blue',)`
instead of
             np.arange(len(inputs)), anomaly, 'blue',)

Cheers

**Comment by be4pro** [comment]
Thank you for the quick hotgym fix.

**Comment by breznak** [comment]
Thanks for reviewing the code, @t0n8 ! 

> wondering if line 234 needs to be changed to 

not necessarily, it could be. But inputs & anomaly are the same length. Feel free to comment directly on the PR for the code changes, or push a commit with improvement. Thanks
