### ISSUE TITLE
How should I cite HTM.core?

### ISSUE THREAD

**Issue by marty1885** [htm-community/htm.core#729]
Hi,
I'm currently writing a report for my graduation project. How should I cite HTM.core in the report? Do you have a preferred way for me to do so?

**Comment by breznak** [comment]
Hi @marty1885 , 

congratulations!  and thank you for reaching out to us about this. 

> How should I cite HTM.core in the report? Do you have a preferred way for me to do so?

I would prefer the 2nd answer in here: https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository 
It suggests a bibtex entry as (I esp. like that there's commit SHA to make research replicable)

```
@misc{Charles2013,
  author = {Charles, P.W.D.},
  title = {Project Title},
  year = {2013},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/charlespwd/project-title}},
  commit = {4f57d6a0e4c030202a07a60bc1bb1ed1544bf679}
}
```

It appears it's now possible to get a DOI for a github repo: 
https://github.blog/2014-05-14-improving-github-for-science/ 
https://guides.github.com/activities/citable-code/ 

- [ ] add "Cite us" section to README with BibTex entry for HTM.core
- [ ] get us a DOI
- [ ] agree with @dkeeney @ctrl-z-9000-times @breznak on Authors: do you want your real name included, or GH @nick , or just "HTM community"? 
  - I'd prefer real names, as I'm still active in academia and counting a citation would help me get closer to PhD :yum: this repo is a community effort with great contributions from many people, but we are the "core developers" for now. Any objections? 

@marty1885 are you in a hurry, or over-the-weekend would be fine?

**Comment by marty1885** [comment]
@breznak My report is due in a month or two. Please take your time :smile: 

> as I'm still active in academia and counting a citation would help me get closer to PhD
Congrats to you too! You are awesome!

**Comment by breznak** [comment]
> due in a month or two. Please take your time

ok, with students (and me too) I'm used to that it could have been very well due today :D

**Comment by marty1885** [comment]
Having good a good task scheduler made my life easier. :P
May you publish the information over at the forums when finished? I know a few there are also doing research but never posts.

**Comment by breznak** [comment]
> May you publish the information over at the forums when finished?

I'm writing up the new stuff, slowly. Got locked in an NDA, so I cannot publish my prev work. 

>  know a few there are also doing research but never post.

it'll be nice to get a "room" on the forums for students/researchers currently writing academic papers on HTM, we could collaborate! :+1:

**Comment by marty1885** [comment]
Oops. I mean the fact that HTM.core have a BibTex entry. Inactive members might have problem finding the information.

> it'll be nice to get a "room" on the forums for students/researchers currently writing academic papers on HTM, we could collaborate! 
Sounds like a cool idea! I'll ask Matt and see what we can do.

**Comment by breznak** [comment]
Proposed BibTex entry: 
```
@misc{htmcore2019,
	abstract = "Implementation of cortical algorithms based on HTM theory in C++ \& Python. Research \& development library.",
	author = "M. Otahal and D. Keeney and D. McDougall and others",
	commit = bf6a2b2b0e04a1d439bb0492ea115b6bc254ce18,
	howpublished = "\url{https://github.com/htm-community/htm.core/}",
	journal = "Github repository",
	keywords = "HTM; Hierarchical Temporal Memory; NuPIC; Numenta; cortical algorithm; sparse distributed representation; anomaly; prediction; bioinspired; neuromorphic",
	publisher = "Github",
	series = "{Community edition}",
	title = "{HTM.core implementation of Hierarchical Temporal Memory}",
	year = "2019"
}

```
Thoughts? 

>  I mean the fact that HTM.core have a BibTex entry. Inactive members might have problem finding the information.

good point, I'll make a PR and then post it on the forums.

**Comment by marty1885** [comment]
Looks good to me! I'm think weather a DOI is a good idea. Looks like the process is quite manual and needs to be done for each release. And a commit hash is a lot more useful.
