### ISSUE TITLE
Unable to install numpy from source on Python 3.8

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#734]
I just installed Python 3.8 on windows 10.   I set my system environment path to include the path to Python 3.8.  This seemed to be a good time to install with a 'virgin' system.
So I then tried a python build, i.e.  `python setup.py install --user --force`

It seemed to find setuptools without having to install before hand. So perhaps setuptools is now part of the core.

While building the egg, it was able to find and install 
- prettytable 0.7.2
- mock 3.0.5
- hexy 1.4.3
- pytest 4.6.5
- numpy 1.17.3  downloaded .zip but failed for lack of a Fortran compiler
```
C:\Users\Dave\AppData\Local\Temp\easy_install-yzk_o6bt\numpy-1.17.3\setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Could not locate executable g77
Could not locate executable f77
Could not locate executable ifort
Could not locate executable ifl
Could not locate executable f90
Could not locate executable efl
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable g95
Could not locate executable efort
Could not locate executable efc
Could not locate executable flang
don't know how to compile Fortran code on platform 'nt'
```

Everything fell apart after that...

**Comment by dkeeney** [comment]
I then used
```
python -m pip install --user numpy
```
And it installed numpy 1.17.3

Then running the python build again `python setup.py install --user --force`  it found:
- found numpy 1.17.3
- downloaded and installed wheel 0.33.6
- downloaded and installed six 1.12.0
- downloaded and installed wcwidth 0.1.7
- downloaded and installed pluggy 0.13.0
- downloaded and installed packaging 19.2
- downloaded and installed more-itertools 7.2.0
- downloaded and installed importlib-metadata 0.23
- downloaded and installed colorama 0.4.1
- downloaded and installed attrs 19.3.0
- downloaded and installed atomicwrites 1.3.0
- downloaded and installed pyparsing 2.4.2
- downloaded and installed zipp 0.5
- it installed pip 19.3.1 
- found setuptools 41.2.0 (added some paths)

build completed successfully.

**Comment by dkeeney** [comment]
Ran `python setup.py test`

Failed in `SdrTest.testDenseInplace`
```
>       copy_time = time.clock()
E       AttributeError: module 'time' has no attribute 'clock'

J:\Projects\AI\htmA\bindings\py\tests\sdr\SDR_test.py:143: AttributeError
```
The 'time' module was imported.  In the python docs I found:
```
Deprecated since version 3.3: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.
```

**Comment by breznak** [comment]
>  So perhaps setuptools is now part of the core.

yes, we've added the setuptools to requirements.txt in one of the recent issues. 

> numpy 1.17.3 downloaded .zip but failed for lack of a Fortran compiler

I've encountered this err, I think on ARM, I believe it's when numpy does not provide the binary package for your combination yet (here Win10, Py3.8, ...) and pip tries to build it from source for you. 

> Then running the python build again python setup.py install --user --force [completed successfully]

Strange..can you uninstall numpy and try again? Either both should fail, or the requirements should pass as well. 

> Deprecated since version 3.3: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.

So, most of these will be python 3.8 related incompatibilities. Py38 is fairly new, but it'll be good to be forced to resolve the deprecations.

**Comment by dkeeney** [comment]
> yes, we've added the setuptools to requirements.txt in one of the recent issues

The point was that setuptools is imported at the top of setup.py and would not be able to run if it was not already installed.  When setup.py finally got to the point where it was installing prerequisites it did find a newer version of setuptools, but there must have been one already installed as part of the core Python 3.8 package.

So, the things we need to address are
- the depecated time.clock()
- how to get numpy installed without building from sources.

I do not understand how `python -m pip install --user numpy` was able to find a binary installation when the install from requirements.txt did not.  Perhaps all that is needed is an entry in the README.md that says to manually install if the htm.core build fails when installing numpy.

**Comment by canepan** [comment]
The same happens to me with Python 3.7 or Python 3.6 (both on ARM).
The message is:
> Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates

**Comment by breznak** [comment]
> The same happens to me with Python 3.7 or Python 3.6 (both on ARM). 

@canepan yours seems a different issue. This is about py3.8, you've confirmed on all py3, but on ARM. So you can move the discussion to a separate issue. 
Btw, if the problem is in installing dependencies on ARM I'm not sure we'll support that. But you can have a look at our ARM builds that manage to install everything needed and build.

**Comment by breznak** [comment]
Bump, we're still not py3.8 ready. Since it's the default python on ubuntu 20.04 LTS, we should look at it soon.
