### ISSUE TITLE
Bug in predictive cells?

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#740]
https://github.com/htm-community/htm.core/blob/7e3d439cbb37a5953dad8bafb81288d635677eca/src/htm/algorithms/TemporalMemory.cpp#L597

I just want to discuss code in getPredictiveCells in TM.
I am not sure about this, but "better close issue then to have hidden bug" :)

` for (auto segment = activeSegments_.cbegin(); segment != activeSegments_.cend();      segment++) {`
There should be `++segment` instead of `segment++ ` in order to use like this i think...

Also why there is `if (segment == activeSegments_.begin() || cell != predictiveCells.back()) {` ?
What is the meaning? If it is the first active segment or the cell is not the last one? 

I can be just confused, so please be patient. :)

**Comment by breznak** [comment]
Thanks for pointing out to a complicated code, please keep doing so while you dig through the codebase! :+1: 

> There should be ++segment instead of segment++ in order to use like this i think...

I think that one was correct. 

> What is the meaning? If it is the first active segment or the cell is not the last one?

literally yes, but why/what's that supposed to mean? See linked PR #743 which should explain it.
