### ISSUE TITLE
Training process of example Mnist

### ISSUE THREAD

**Issue by be4pro** [htm-community/htm.core#749]
Hey guys,

I'm curious. In mnist.py, why do we go for `img, lbl = random.choice(training_data)`, rather than `img, lbl = training_data[i]`, given [training_data has already been shuffled](https://github.com/htm-community/htm.core/blob/f6d97c90ab30a4823431ba446a01cf506f3ebf4f/py/htm/examples/mnist.py#L90)?

**Comment by breznak** [comment]
you're right, either of them is enough :+1:

**Comment by be4pro** [comment]
I felt like shuffle + `img, lbl = training_data[i]` is more suitable. If we cancel the shuffle and only use `random.choice()` in the for loop, it might pick up some data points repeatedly.

**Comment by breznak** [comment]
@be4pro will you make a PR with a fix?

**Comment by be4pro** [comment]
OK, I will. :+1:
