### ISSUE TITLE
Streaming values into NTA_THROW does not work.

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#753]
After the Exception code cleanup PR #742  the error messages streamed into NTA_THROW no longer work.

```
  try {
    NTA_THROW << "This error msg";
  } catch (const Exception &e) {
    EXPECT_STREQ(e.getMessage(), "This error msg");
  }
```
I added this to the end of ExceptionTest.hpp and it fails.  e.getMessage() is empty.
Tried this on Windows 10 using MSVC 2019.

But what I really want is something like: `e.what()` to return
```
    Exception:  <full path to module>(<line number>) message:  <message goes here>
```
It is not obvious to me what changed that broke it.

**Comment by breznak** [comment]
Thanks David for finding this and sorry for the bug!

**Comment by dkeeney** [comment]
Found the problem.  The copy constructor should be something like:
```
  Exception(const Exception& copy):
    std::runtime_error("")	{
    filename_ = copy.filename_;
    lineno_ = copy.lineno_;
    message_ = copy.getMessage();   // will add in the streamed fields
    stackTrace_ = copy.stackTrace_;
  }
```

Could use std::move( ) on those assignments I guess but this is not a high use function.
