### ISSUE TITLE
Little bug in MSVC build 

### ISSUE THREAD

**Issue by LucaCerina** [htm-community/htm.core#770]
Hello,
I had a problem in which MSVC version was not recognized because vswhere returned an empty array (see also #https://github.com/Microsoft/vswhere/issues/103)

Adding `-products *` to the arguments of vswhere solves the problem

**Comment by breznak** [comment]
Hi, thanks for the report and finding a solution :+1: 
Would make for a nice first PR? :wink:

**Comment by LucaCerina** [comment]
Added on #771
