### ISSUE TITLE
Parameter optimization not working on Windows?

### ISSUE THREAD

**Issue by indy-3rdman** [htm-community/htm.core#774]
Hi!
Just tried to run the example from [https://github.com/htm-community/htm.core/tree/master/py/htm/optimization](https://github.com/htm-community/htm.core/tree/master/py/htm/optimization) on Windows:

`python -m htm.optimization.ae -n 7 --memory_limit 14 -v --swarming 100 mnist.py`

Unfortunately it throws the following error:
ModuleNotFoundError: No module named 'resource'

It is executing fine under Linux. 
Did some quick research and came across this [https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)

Could the resource module be replaced by something else that is supported cross platform?

Cheers!

**Comment by ctrl-z-9000-times** [comment]
Hello,

I think this issue has come up before...
I don't know of any cross platform replacement for the `resources` module.

Sorry

**Comment by indy-3rdman** [comment]
How about this one?

```
diff --git a/py/htm/optimization/ae.py b/py/htm/optimization/ae.py
index de0d863c9..295f576c5 100644
--- a/py/htm/optimization/ae.py
+++ b/py/htm/optimization/ae.py
@@ -120,7 +120,7 @@ import datetime
 import tempfile
 import threading
 from multiprocessing import Process, Pipe
-import resource
+import psutil
 import re
 import numpy as np
 import scipy.stats
@@ -433,6 +433,8 @@ class Laboratory:
     def save(self):
         with open(self.lab_report + '.tmp', 'w') as file:
             file.write( str(self) )
+        if  os.path.exists(self.lab_report):
+            os.unlink(self.lab_report)
         os.rename(self.lab_report + '.tmp', self.lab_report)

     def run(self, processes,
@@ -508,8 +510,10 @@ class Worker(Process):
         print("Started: " + time.asctime( time.localtime(start_time) ) + '\n')
         # Setup memory limit
         if self.memory_limit is not None:
-            soft, hard = resource.getrlimit(resource.RLIMIT_AS)
-            resource.setrlimit(resource.RLIMIT_AS, (self.memory_limit, hard))
+            if sys.platform.startswith('linux'):
+                p = psutil.Process()
+                soft, hard = p.rlimit(psutil.RLIMIT_AS)
+                p.rlimit(psutil.RLIMIT_AS, (self.memory_limit, hard))

         exec_globals = {}
         try:

```
At least allows me to execute it on windows as well.

**Comment by ctrl-z-9000-times** [comment]
That looks fine!
Could you open a Pull Request with this diff?  Then we can comment on it, and I can accept these changes into the code base.

Thank you

**Comment by Thanh-Binh** [comment]
@ctrl-z-9000-times how can you find the minimum and maximum values of SP or TM Parameters?

**Comment by ctrl-z-9000-times** [comment]
@Thanh-Binh 
If I recall correctly, invalid parameters cause the SP & TM to crash the process, and the optimizer program detects the crash and marks the parameters as invalid.  It then resets the optimizing process to a known-good state.

**Comment by Thanh-Binh** [comment]
@ctrl-z-9000-times 
I will give a simple sample.
Suggest, you want to find the min and max value of 2 SP parameters.
If you run SP everytime by changing only P1 from the default value in the negative/positive direction untils process is crashed, so you can estimate the min and max value by given P2.
After that you can find out a valid 2D-region of P1, P2.
In the 2nd step of optimization, you find the best set of parameters in 2D-region according to some optimization object values.
How long does your process run in your laptop?

**Comment by breznak** [comment]
> If you run SP everytime by changing only P1 from the default value in the negative/positive direction untils process is crashed, so you can estimate the min and max value by given P2. 

this would be a generic question about multidimensional optimization, parameter optimization. I think here are implemented methods GridSearch (brute force) and particle swarm optimization (PSO). But let's discuss further questions separately and keep this topic focused on the OP's windows compatibility issue.
