### ISSUE TITLE
RDSE non-overlap with differences => resolution is not guaranteed

### ISSUE THREAD

**Issue by LucaCerina** [htm-community/htm.core#777]
Hello,
I am trying to use the Random Distributed Encoder to encode a set of scalar values. Then I am using the SDRClassifier to decode encoded values.

The problem arises when I try to optimize the sparsity to limit bitsize or number of activeBits.
On a Windows machine with MSVC2019, I am encoding values from 75 to 140 with resolution of 0.25.
Values are transformed in categories before encoding as explained in RDSE examples.

I optimize bitsize to guarantee at least 2 times the number of unique values (260 in this case) and obtain an SDR with 24bits and 2 active bits. This is what happens:
5       76.25   [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]       76.5
6       76.5     [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]       76.5
This happens with both close and distant values
36      84.0     [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0]       95.25
81      95.25   [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0]       95.25

Increasing active bits does not solve the problem (here with 4), but at least it limits it to close values. The same goes with increasing SDR size
29      82.25   [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0]       82.5
30      82.5     [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0]       82.5

I fear it could be a system level problem and I will try to run everything also on a Linux machine, otherwise I believe it will be a problem rooted in the murmurhash.

If you have any ideas or possible solutions (without saving past encodings) let me know

**Comment by breznak** [comment]
Thanks for reporting the issue! 

> fear it could be a system level problem and I will try to run everything also on a Linux machine, 

I wouldn't think this is a platform problem, but please try. Also check that on the HW that has the problem, you pass all the unit tests (`./build/Release/unit_tests`) 
Also you can try running the code in Debug, there are extra asserts there. 

Can you give me a code of a reproducible test-case? 

> otherwise I believe it will be a problem rooted in the murmurhash. 

we used to have another approach than MurMur, I'm not sure if it's still avaiable (or if you can go in git history and try without that)? 

I'll CC @ctrl-z-9000-times who implemented that code. I won't unfortunately have time until mid next week to look into this more. If noone answers, please ping me around then again.

**Comment by LucaCerina** [comment]
Another partial solution I see would be to accept 1-2 parameters for the range (like the regular Scalar Encoder) and calculate a priori the hash collision probability and output a warning if it's too high, or automatically increase size to fit a threshold.

I'll polish a bit the code and attach it here for reproducibility

**Comment by breznak** [comment]
> and calculate a priori the hash collision probability and output a warning if it's too high, or automatically increase size to fit a threshold. 

I recall David commenting that it's the users responsibility to use reasonable settings to avoid collistions. 
- is this happening in some demo code? 
- can you reproduce with ("normal") large sizes? 
- and yes, warning that "your settings might not be right" would be great!

**Comment by LucaCerina** [comment]
[testcode.zip](https://github.com/htm-community/htm.core/files/4235938/testcode.zip)
This is the code I used.

- The minimum setup that provides few errors is 260 with 2 active bits (260 is the number of unique combinations I need). But even in this case, the number of unique encodings is not always 260. it goes non-deterministically between 254 and 260.

- With very large values like 2048 and 40 active bits the problem disappears since hash collision probability falls really low.

I agree on leaving the responsibility to the user to avoid collisions, but debugging the problem and finding that some checks are "left to the reader" was a bit underwhelming ^^'

**Comment by breznak** [comment]
> With very large values like 2048 and 40 active bits the problem disappears since hash collision probability falls really low 

I'll try to see the example, but based on the above, this is likely expected behavior. If we figure how to detect and warn on an insufficient config, it'd be good. (Maybe just warn when size > 500?)

**Comment by breznak** [comment]
> I agree on leaving the responsibility to the user to avoid collisions, but debugging the problem and finding that some checks are "left to the reader" was a bit underwhelming ^^' 

Have you been able to automate some of the check logic somehow? 

Reclassifing as enhancement.
