### ISSUE TITLE
ERROR: ERROR: Could not find a version that matches htm-core[examples]

### ISSUE THREAD

**Issue by RDaneelOlivav** [htm-community/htm.core#781]
Hi,

When installing it through this command with pipenv:
pipenv install -i https://test.pypi.org/simple/ htm.core[examples]

It apperas this error:

ERROR: ERROR: Could not find a version that matches htm-core[examples]
No versions found

Is there some way to get rif of this error? Do we have to specify the version somewhere?
Thanks

**Comment by dkeeney** [comment]
On Linux pypi is very picky.  The package for release 2.0.22 was built for Python 3.7.6 and Ubuntu 7.4 or later.  If you don't have a match I suggest downloading the sources from https://github.com/htm-community/htm.core/releases  htm_core-v2.0.22-linux64.tar.gz  and then do a full build.  It does not take very long. The instructions are in README.md 

Sorry.

**Comment by breznak** [comment]
> pipenv install -i https://test.pypi.org/simple/ htm.core[examples] 

you may also try without the `[examples]`, so 
` pip install -i https://test.pypi.org/simple/ htm.core` 
(and may manually install the dependencies for examples, if needed) 

Closing, please reopen if you still have troubles.
