### ISSUE TITLE
Region name changes

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#784]
Change the names of the following regions.
RDSERegion --> RDSEEncoderRegion
ScalarSensor --> ScalarEncoderRegion
VectorFileEffector --> FileOutputRegion
VectorFileSensor --> FileInputRegion

While we are at it,
src/examples/hotgym has nothing to do with the python hotgym example so it should be called HelloSPTP. Then we should build C++ and NetworkAPI versions of the python hotgym example.

**Comment by dkeeney** [comment]
I am starting a new PR for this issue.

I am starting to question if it is correct to change this:  RDSERegion --> RDSEEncoderRegion
The encoder is "RDSE" or "RandomDistributedScalarEncoder".
So should the region name be 
- RDSERegion
- RDSEEncoderRegion
- RandomDistributedScalarEncoderRegion

Remember this is both the class name and the name that is entered as text in the configurations.

@breznak do you have a preference?

**Comment by dkeeney** [comment]
Renames for the examples:
src/examples/hotgym  =>  src/examples/hello
src/examples/napi_sine => src/examples/napi_hello

hopefully we will eventually add
- Python version of hotgym   (we have this one)
- C++ version of hotgym.
- NetworkAPI version of hotgym
- REST version of hotgym

**Comment by breznak** [comment]
> I am starting to question if it is correct to change this: RDSERegion --> RDSEEncoderRegion 

I see your point (it's the same as LED diodes :) ), 
- my idea was for input/encoder regions to show that in the name, thus `*EncoderRegion` (same as `*Encoder` for the encoder classes)
- I think the shorter RDSEEncoderRegion is fine (but not strong opinion if you dont like the duplicit E)
