### ISSUE TITLE
Gcc-10  build fails

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#788]
I'm testing build on Ubuntu 20.04 (soon to come LTS) with `gcc-10`. 

`cmake` stage fails on `Release` : 

```
95%] Built target gtest_main
[ 97%] Building CXX object mnist_data/mnist-build/CMakeFiles/mnist_example.dir/main.cpp.o
[100%] Linking CXX executable mnist_example
[100%] Built target mnist_example
-- Results from external build:
--   common_INCLUDE_DIRS = /home/mmm/devel/HTM/htm-community/nupic.cpp/external/common
--   common_LIBRARIES = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libcommon.a
--   yaml_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-src/include
--   yaml_LIBRARIES = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-build/libyaml.a
--   yaml_DEFINE = YAML_PARSER_libYaml
--   eigen_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/eigen/eigen-src
--   gtest_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/gtest/googletest-src/googletest/include
--   gtest_LIBRARIES = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/gtest/googletest-build/googletest/libgtest$<$<CONFIG:Debug>:d>.a
--   mnist_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/mnist_data/mnist-src/include
--   mnist_SOURCE_DIR = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/mnist_data/mnist-src
--   cereal_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/cereal/cereal-src/include
--   digestpp_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/digestpp/digestpp-src
--   cpp-httplib_INCLUDE_DIRS = /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/cpp-httplib/cpp-httplib-src
-- Configuring htm_core src
-- MERGE_STATIC_LIBRARIES LIB_TARGET=htm_core, STATIC_LIBS = htm_core_solo;/mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-build/libyaml.a;/mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libcommon.a
-- MERGE_STATIC_LIBRARIES:     htm_core_solo
-- MERGE_STATIC_LIBRARIES:     /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-build/libyaml.a - non-target lib.
-- MERGE_STATIC_LIBRARIES:     /mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libcommon.a - non-target lib.
-- ExpandStaticLib: LIB_TARGET=htm_core_shared, src-lib=/mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-build/libyaml.a
CMake Error at src/ExpandStaticLib.cmake:68 (message):
ExpandStaticLib: obj extraction process failed exe_result='No such file or
directory'
Call Stack (most recent call first):
src/CMakeLists.txt:298 (ExpandStaticLib)

```

interesting passes OK with `Debug`.

**Comment by breznak** [comment]
CC @dkeeney if you have better idea where the err originates, I'm a bit confused by the message.

**Comment by breznak** [comment]
Edit: gcc-10 is still experimental, ubuntu 20.04 comes with `gcc-9` as default which builds just fine. So we're good :+1:

**Comment by dkeeney** [comment]
Welcome back @breznak 
The merge static libraries is a script that combines static libraries into one library.
I will look at it and see if I can figure out what is going wrong.

**Comment by breznak** [comment]
OT: yep, I took a break, now full back IN. How are you doing? 
Some of my on-plate now is to see (benefits) of the new compilers, gcc-9/10, and if we can switch to c++17 on all platforms. Then look at multithreading. 
I'd also be interested in performance comparison (overhead) in "native c++" hotgym, (`hello`), NetworkAPI (`hello_napi`) and REST (`hello_rest`). What I'm (just unverified thought) thinking is if we could use MQTT (instead of custom Links) and support `ROS` ?

**Comment by dkeeney** [comment]
> How are you doing?
I am doing fine.  I also slowed down a little while you were away.

>  and if we can switch to c++17 on all platforms. Then look at multithreading.
Sounds good.

>  use MQTT (instead of custom Links)
Hmmm, that would be a cool idea.

**Comment by dkeeney** [comment]
```
ExpandStaticLib: LIB_TARGET=htm_core_shared, src-lib=/mnt/store/devel/HTM/htm-community/nupic.cpp/build/ThirdParty/libyaml/libyaml-build/libyaml.a
CMake Error at src/ExpandStaticLib.cmake:68 (message):
```
It appears that it is not finding libyaml.a
This is one of those third-party libraries that we download and is build as part of the dependency processing.   If you have ubuntu 20 running, can you check `build/ThirdParty/libyaml/libyaml-build`.  There should be a log there someplace that explains why the library does not get built.

**Comment by breznak** [comment]
>  If you have ubuntu 20 running, can you check build/ThirdParty/libyaml/libyaml-build. There should be a log there someplace that explains why the library does not get built. 

I was checking for the `libyaml.a` and it exists ... 
oh, turns out the binary was a remainer fron older gcc version build. I needed to `git clean -xdf` from the repo dir, and rebuild the dependencies again. 
My mistake, sorry for the noice, David.

**Comment by breznak** [comment]
Btw, gcc-10 works well too!

**Comment by dkeeney** [comment]
Oh, glad that was all it was. 👍
