### ISSUE TITLE
pip version

### ISSUE THREAD

**Issue by steinroe** [htm-community/htm.core#802]
Hi,

can we get the current version to pip? We are at 2.1.0 and the latest version on pip is 2.0.18.

Best
Philipp

**Comment by dkeeney** [comment]
I am trying to figure out which version you are referring to.  I must be missing something.

The latest version of pip is 20.1.1   see https://pypi.org/project/pip/

htm.core is asking for anything greater than or equal to 19.3.1 see https://github.com/htm-community/htm.core/blob/master/requirements.txt

**Comment by breznak** [comment]
No, it’s us 🙂the htmcore version on pypi

-- 
Marek Otahal :o)

**Comment by dkeeney** [comment]
Oh, you mean the htm.core version in PyPi.  I  got it.

@breznak, can you handle this one?

**Comment by steinroe** [comment]
Thanks! Would be great bc I dont want to install cmake on a workstation and need the current version to run my stuff.

**Comment by breznak** [comment]
sorry, I'll try to look at it over the weekend. The reelease & pipy logic isn't automated yet. Maybe we should push only the linux pips, if that works? 

> I dont want to install cmake on a workstation  

as a workaround, one might install cmake from pip/conda: https://pypi.org/project/cmake/

**Comment by breznak** [comment]
@steinroe please test, this should be now :heavy_check_mark:
