### ISSUE TITLE
Need to set ARCHFLAGS in build

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#844]
See https://discourse.numenta.org/t/installing-with-mac-and-virtual-environments/7666/5
```
  export ARCHFLAGS="-arch x86_64"
```

I thought ARCHFLAGS was being set in the build setup but apparently not for MacOS.

**Comment by breznak** [comment]
Thank you for tracking the community problems on the Forums, David! 

>  set in the build setup but apparently not for MacOS. 

I haven't read the whole thread properly, but I'd be surprised if it's extra needed or if it helps - as apparently our CI runs on MacOS and we don't do anything specific, all is done in setup.py. 


..actually, read the thread, it user is able to run htm.core (only has some API syntax problems), the answer with ARCHFLAGS is unrelated to us or incorrect. 

Closing this as wontfix, non-issue.
