### ISSUE TITLE
Mistakenly closing all PRs? 

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#850]
@Zbysekz some mistake, a virus, or have you decided going berserk on all our PRs and close them? :smiley:

**Comment by Zbysekz** [comment]
Oh shit sorry !!! , i don't know what happened

**Comment by Zbysekz** [comment]
i tried to clean up my fork but .... WTF

**Comment by breznak** [comment]
I've restored all branches and reopend all PRs that were closed by this event. 
Just hope we don't get a ban from CI, as now some 20 CI run at once.

**Comment by Zbysekz** [comment]
Really sorry... hope no damage was done :((((

**Comment by Zbysekz** [comment]
I have write permissions to this repo? I thought i don't...

**Comment by breznak** [comment]
> i tried to clean up my fork  

ok, that explains it. apparently you've deleted your branches but pushed to HERE (origin, community, or which name you have) and not to your fork, deleting all the branches and that resulted in closing the PRs. 
No prob, explained :) You'd be a good scrum master :wink:

**Comment by breznak** [comment]
> I have write permissions to this repo? I thought i don't... 

neither did I :) I might check the settings and tighten up a bit. (no offense, just to see who actually can do what). I guess it comes from the "HTM community" membership where I added you recently for the work in PandaVis.

**Comment by Zbysekz** [comment]
> neither did I :) I might check the settings and tighten up a bit. (no offense, just to see who actually can do what). I guess it comes from the "HTM community" membership where I added you recently for the work in PandaVis.

Yes please do, so i can be sure that i can mess up only with my repo :).
Yeah probably it's connected with the membership...
Bloody SourceTree, it appeared to be pushing on right remote, but i am not so sure...
