### ISSUE TITLE
Temporal Memory with only external distal synapses

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#852]
In order to proceed with [2D object recognition project](https://github.com/htm-community/htm-2d-object-modeling) i would need to have Temporal Memory without internal distal synapses.

TM there is applied on sensory layer, distal synapses goes just from Location Layer. No distal connection internally in Sensory Layer.

As i see there is no possibility now with TemporalMemory algorithm in htm.core. There are the external predictive inputs & external predicitive winners and those are put atop of the internal state.
See [TemporalMemory ActivateCells()](https://github.com/htm-community/htm.core/blob/871ece68d8e94ac508d44c245bd30f4b820754de/src/htm/algorithms/TemporalMemory.cpp#L293)

Any suggestions? I think this is good change, generalization & is compliant with the theory.

**Comment by Zbysekz** [comment]
I am imagining adding one parameter that says if the internal synapses should be formed or not.
Defaultly true so no interface & behaviour change for current implementations.

**Comment by Thanh-Binh** [comment]
@Zbysekz as far as I know, there is an C++-implementation of Numenta for experiments, named "ApicalTiebreakTemporalMemory"
at https://github.com/numenta/htmresearch-core/tree/master/src/nupic/experimental
As far as I know, it is better than TM and allows you for doing your task.

**Comment by Zbysekz** [comment]
P.S. for explanation regarding the 2D recognition project - sensory layer must NOT learn sensorimotor sequences to enable path integration _The location layer projects to the dendritic segments of the sensory layer (Figure 3, connection 2)......_ from [Locations paper](https://www.frontiersin.org/articles/10.3389/fncir.2019.00022/full)

**Comment by Zbysekz** [comment]
Found apical tie-break already implemented in python in our repo:
[apical_tiebreak_temporal_memory.py](https://github.com/htm-community/htm.core/blob/master/py/htm/advanced/algorithms/apical_tiebreak_temporal_memory.py)

**Comment by breznak** [comment]
Shall we close this with `ApicalTM` being what you need? Or does it make sense to port (parts) of the functinality to the "main TM"? 

> As far as I know, it is better than TM and allows you for doing your task. 

we should validate that and if really outperforms in general, replace it to be the default TM. (comparison on NAB would be a good test)

**Comment by Zbysekz** [comment]
I am not sure right now, need to dig in more into advanced examples code, then i will close it/rename it to fit the purpose.

**Comment by Zbysekz** [comment]
For now, the apical_tiebreak_temporal_memory.py can be used in 2D recognition project (already tested), later on in the future, could be ported to c++ code for performance improvement.

**Comment by Thanh-Binh** [comment]
@Zbysekz the c++ Version is already available

**Comment by Zbysekz** [comment]
@Thanh-Binh  Really? where?

**Comment by Zbysekz** [comment]
Ah in the link that you gave before... so that's nupic, but just not ported to htm.core.... right, thanks

**Comment by Thanh-Binh** [comment]
See my answer in this thread 19 days ago
