### ISSUE TITLE
setup.py install file not found error

### ISSUE THREAD

**Issue by Tann10** [htm-community/htm.core#865]
I am trying to install htm.core from source in Python 3.7 on windows 10. I get following error when I execute python setup.py install
![image](https://user-images.githubusercontent.com/54607338/88874776-2a60e100-d220-11ea-9ed2-8a44b188bd0c.png)

Please let me know if there is a quick fix for this! Thank you.

**Comment by dkeeney** [comment]
If you are using Anacondra (and it appears that you are) then you must use the Command Prompt setup for Anacondra, not the normal Command Prompt.
Then confirm that you have Microsoft Visual studio 2019 installed (I think you do).
cd to the top folder of the repository.
Then use the following command to build with the Python bindings.
```
 python setup.py install --user --force
```

I hope that helps.

**Comment by Tann10** [comment]
@dkeeney Thank you so much for your reply. I tried to execute the setup.py from anaconda prompt, I am still seeing the same error. I want to install this package in a virtual env. Is that why its failing?

**Comment by dkeeney** [comment]
I don't think that is the problem.

It failed when trying to locate Visual Studio 2017 or 2019.  It is expecting to find the installer at "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe".   Please look at that location to see if you have it installed there.  
If not, perhaps I need a better way to check that it is installed.

**Comment by dkeeney** [comment]
You are making progress.
Try deleting the 'build' folder and try again. You may have something cached in cmake from the previous attempts.

What this is pointing out is that my logic to tell you that "Visual Studio was not installed" is not working.  The objective is to tell you before it starts running cmake.

**Comment by Tann10** [comment]
I still see the same error even after deleting the build folder and running python setup.py install..

**Comment by dkeeney** [comment]
I am out of ideas.  I am trying to reproduce this myself but it all works.
I have Visual Studio 2019 running on my windows 10.    (I also have VS 2015 and VS 2017 installed)
I am using standard Python 3.8.5 but we use 3.7 in our regression tests so I know it works.  I also have Anaconda Python 3.7.4 in the Anaconda prompt.  

Grasping at straws...
  Can you run this command in your Anaconda prompt window and post the output?
```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
```
I am expecting to find a "displayName" entry that contains "2019" to declare that Visual Studio 2019 is installed.
`displayName: Visual Studio Community 2019`
Perhaps something else in the output will give me a clue as to what is going on.

**Comment by Tann10** [comment]
Here is the output I get.  I can see that Visual Studio is installed. 
![image](https://user-images.githubusercontent.com/54607338/89181542-481da580-d594-11ea-9448-7744f190c16a.png)

Anyway, I used pip to install the package right now and that worked. As I am able to use the package I think I am good! Thank you so much for your help.

**Comment by dkeeney** [comment]
Thank you for working with me on this. Sorry I could not have been more helpful.
I would like to find the cause so I will continue to watch for anyone else that is having this problem and eventually we may find the clue that leads to the solution.

**Comment by Tann10** [comment]
No problem, thank you for helping in debugging this issue. I will solve this issue then!
