### ISSUE TITLE
can't import so files from bindings

### ISSUE THREAD

**Issue by sonjh17** [htm-community/htm.core#868]
Hey guys.
After I successfully installed htm, Ive been trying to run the example codes (hotgym.py and mnist.py).
I realized that in both of these files I am having trouble with importing the so files in binding

This is the error I've been getting

ImportError: dlopen(/Users/user/Library/Python/3.8/lib/python/site-packages/htm.core-2.1.15-py3.8-macosx-10.15-x86_64.egg/htm/bindings/algorithms.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/user/Library/Python/3.8/lib/python/site-packages/htm.core-2.1.15-py3.8-macosx-10.15-x86_64.egg/htm/bindings/algorithms.so
  Expected in: flat namespace
 in /Users/user/Library/Python/3.8/lib/python/site-packages/htm.core-2.1.15-py3.8-macosx-10.15-x86_64.egg/htm/bindings/algorithms.so

I've been searching to use the common solutions to resolve the issue but not with much success.
Could anyone help out please?
I am on python 3.8.5 on macosx 10.15 as you can see
Thanks in advance

**Comment by Zbysekz** [comment]
Hello @sonjh17,
This would be probably related to issues that we have with python 3.8. If you can, please use python 3.7x and report here if it was successful. Thank you

**Comment by breznak** [comment]
Closing, please reopen when active.
