### ISSUE TITLE
NetworkAPI: Region getParameters() bug

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#875]
Code to reproduce:
```
Network net;
// create an SP region with default parameters 
std::shared_ptr<Region> region1 = net.addRegion("region1", "SPRegion", "");  // use default configuration

VERBOSE << region1->getParameters();
```

causing
**C++ exception with description "Exception: Region.cpp(652) message: Error getting parameter region1.spInputNonZeros; CHECK FAILED: "initialized_" " thrown in the test body.**

causing SIGSEG when called in same way from python.

This is specific only to SPRegion

**Calltrace:**
Region.cpp : getParameterJSON()
SPRegion : getParameterArray()
https://github.com/htm-community/htm.core/blob/68ca06b1fb6e0c424c8f8ca19cf1750ca7c17477/src/htm/regions/SPRegion.cpp#L734-L747

It is because in getParameters it try to get all parameters including spInputNonZeros, which is empty because no input was yet given. 
I don't understand why these inputs/outputs are here, becasue these are not parameters.

We already have getOutputData() and getInputData() so why is this here?

I need this function to work properly to get what parameters are in region to setup database before any network.run...

**Comment by dkeeney** [comment]
> We already have getOutputData() and getInputData() so why is this here?

getOutputData() and getInputData() are new.  originally the only way to get these outputs into an app was via these parameters. I kept those parameters for backward compatibility.

But they do need to work.
During initialization all buffers are initialized. Before initialization they could be in an unknown state. Perhaps that is causing the problem. So we need some logic to determine if they have been set.

**Comment by Zbysekz** [comment]
sorry i didn't put the net.initialize() in the example given above.

Even after net initialization it throws this exception...
