### ISSUE TITLE
NetworkAPI - getSpec causes double free exception

### ISSUE THREAD

**Issue by Zbysekz** [htm-community/htm.core#877]
I stuck with another bug, this time it is the function getSpec() in region, when called from python.

In my opinion this is pybind related bug.

See unit test [https://github.com/Zbysekz/htm.core/tree/getSpecDoubleFree](https://github.com/Zbysekz/htm.core/tree/getSpecDoubleFree)

or the code:
```
def testGetSpec(self):
    """
    Test of region.getSpec() function. Testing if pybind pointers are correctly handled
    """
    net = Network()
    dateRegion = net.addRegion('dateEncoder', 'DateEncoderRegion',
      str(dict(timeOfDay_width=30,
           timeOfDay_radius=1,
           weekend_width=21)))

    dateRegion.getSpec()# twice times to check if no double free arises
    dateRegion.getSpec()
```

Basically, it happens when any region getSpec is called twice.
Firstly i thought it is because of 
`  const std::shared_ptr<Spec> &getSpec() const { return spec_; }`

returning reference, but that was not it.  Then i tried also `py::return_value_policy::reference` but also no success.

**Comment by Zbysekz** [comment]
Note that first time it gets spec object correctly, second time it is returned None. I think python destroys the spec object twice. But it uses shared ptr so i don't understand....

**Comment by dkeeney** [comment]
Hmmm,  this is an interesting bug.
The spec pointer is placed in a shared_ptr and cached in RegionImplFactory line 136.  It does this when the region type is registered.  

Since pybind11 passes the shared_ptr to Python it should not be freeing the pointer.  It can delete the shared_ptr object...that would be ok because there will be another instance in the cache.  

But I wonder if it is because it is passing a reference to the shared pointer rather than a copy of the object itself. Did you try changing the signature of getSpec( ) in Region.hpp and RegionImplFactory.hpp?  I don't know what it might do to other code if we did that...we would have to check each call to confirm that it would work ok to do that.

**Comment by Zbysekz** [comment]
I removed & from getSpec() so it does return copy of shared ptr instead of reference. No need to change enywhere else. But result was the same. (I think i didnt change regionImpFactory.hpp)

**Comment by Zbysekz** [comment]
I want to correct my previous post, i probably haven't recompile all correctly. I again tried changing returning copy of object instead of reference.
So code change in Region and regionImpFactory sources and headers.

Behaviour:

I can call dateRegion.getSpec() how many times i want and keep returning spec object so that is fine.
But after script finish, there is segmentation fault.

**Comment by Zbysekz** [comment]
Problem solved,

pyEngine.cpp line 224

there should be 
`py::class_<Spec, std::shared_ptr<Spec>> py_Spec(m, "Spec");`
instead of 
`py::class_<Spec> py_Spec(m, "Spec");`

According to [https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr](https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr)
if no holder type is specified, unique_ptr is used so when python reference count is zero (end of the script), it gets deallocated, which we don't want.

**Comment by dkeeney** [comment]
> `py::class_<Spec, std::shared_ptr<Spec>> py_Spec(m, "Spec");`

Oh, good find.  👍 
I am in the middle of replacing a hard drive on a friend's laptop and could not spend any time on this issue.  So I am glad you were able to locate the problem.

**Comment by Zbysekz** [comment]
> > `py::class_<Spec, std::shared_ptr<Spec>> py_Spec(m, "Spec");`
> 
> Oh, good find. 👍
> I am in the middle of replacing a hard drive on a friend's laptop and could not spend any time on this issue. So I am glad you were able to locate the problem.

No problem David, at least i was forced to learn something about pybind :) 👍
