### ISSUE TITLE
Cereal includes missing from build/Release/include

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#885]
There was a comment mentioning that there was an error trying to build an app using the htm.core library.  I cannot locate the comment now but I thought I should try this myself.

So I made a copy of napi_hello and tried to build it outside of CMake.  I found several problems.
- the Cereal includes were not found even if I referenced build/Release/include in the -I.
- htm/os/ImportFileSystem.hpp did not have the right logic.  Was trying to include boost.
- for timer.hpp the global SPEED was not initialized correctly.  (globals should declared extern but allocated in a .hpp)

**Comment by breznak** [comment]
> there was an error trying to build an app using the htm.core library.[...] I should try this myself.

thanks for trying that scenario! We only modify directly in the repo, but never actually linked htm.core as a 3rd party. This is a great test. 

> napi_hello and tried to build it outside of CMake 

w/o cmake completely, or just outside of "our" cmake repo? 

> htm/os/ImportFileSystem.hpp did not have the right logic. Was trying to include boost. 

did you build before the htm.core yourself on the machine, or using the binary release? Some ifdefs determine the c++ version I guess.. if that get's too nasty, we could jump the gun and just do c++17 and drop boost (?)

**Comment by dkeeney** [comment]
> w/o cmake completely, or just outside of "our" cmake repo?

w/o cmake completely.  The way a user might try to use htm.core.
For example, here is the debug build (without python).
```
#! /bin/sh
# This is how to build in Debug mode and run the example
# First build htm.core as debug.
#      cmake ../.. -DCMAKE_BUILD_TYPE=Debug
# We use -std=c++17 to get <filesystem> so we can avoid using the boost library.
# The -I gives the path to the includes needed to use the library.
# The -L gives the path to the shared htm.core library location at build time.
# The LD_LIBRARY_PATH environment variable points to the htm.core library location at runtime.

g++ -g -o napi_hello -std=c++17  -I ../build/Debug/include napi_hello.cpp -L ../build/Debug/lib -lhtm_core -lpthread -ldl 

export LD_LIBRARY_PATH=.:../build/Debug/lib:$LD_LIBRARY_PATH
./napi_hello
```

**Comment by dkeeney** [comment]
I think I have the includes fixed but now I am getting some undefined symbols.
```
ave@ubuntu1810:~/htm.core/examp$ ./debugBuild.sh 
/usr/bin/ld: /tmp/ccIclmkO.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::BinaryInputArchive>(cereal::BinaryInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccIclmkO.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::PortableBinaryInputArchive>(cereal::PortableBinaryInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccIclmkO.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::JSONInputArchive>(cereal::JSONInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccIclmkO.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::XMLInputArchive>(cereal::XMLInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccIclmkO.o:(.data.rel.ro._ZTVN3htm5ArrayE[_ZTVN3htm5ArrayE]+0x60): undefined reference to `htm::ArrayBase::allocateBuffer(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
collect2: error: ld returned 1 exit status
```

In all of them it looks like it wants us to pass in the allocator( ).

**Comment by breznak** [comment]
> For example, here is the debug build (without python). 

I sense a great Readme update :)

**Comment by dkeeney** [comment]
>  it wants us to pass in the allocator( ).

Well...maybe it just wants the signature to have an std::vector that has the allocator.

**Comment by Zbysekz** [comment]
> There was a comment mentioning that there was an error trying to build an app using the htm.core library. I cannot locate the comment now

I was the one who create question here [https://github.com/htm-community/htm.core/issues/880](https://github.com/htm-community/htm.core/issues/880)


> - the Cereal includes were not found even if I referenced build/Release/include in the -I.

Yes i solved this by just including include folder in cereal-source folder. But this is probably hack, and should not work like this?

> - htm/os/ImportFileSystem.hpp did not have the right logic. Was trying to include boost.

I struggled with this, but found that i was not compiling with c++17 (i am on linux, and in the cmake or make logic, there is "switch" that inhibit using boost if C++ is new enough).  So specifying `-std=c++17` option for compiler miscellaneous flags (in  eclipse)

**Comment by dkeeney** [comment]
Thank you @Zbysekz for bringing our attention to this problem.

This PR addresses the problem of the missing Cereal includes by adding them to the install so they are added to build/Release/include along with rest of the includes needed to use the library.  I also added htmllib.hpp which will be needed by the RESTapi component.

For Windows MSVC the default for the compiler is C++17 but for GCC on Linux it is C++14.  So for a Linux compiler you will need the -std=c++17 flag to enable filesystem.  I added a comment to that effect to the README.

But the problem remains, when building with 
```
g++ -g -Og -o napi_hello -std=c++17  -I ../htm.core/build/Debug/include napi_hello.cpp -L ../htm.core/build/Debug/lib -lhtm_core -lpthread -ldl
```

Note: this is a copy of napi_hello.cpp in a folder just outside of the repo.
```
/usr/bin/ld: /tmp/ccGdNoQ9.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::BinaryInputArchive>(cereal::BinaryInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccGdNoQ9.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::JSONInputArchive>(cereal::JSONInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccGdNoQ9.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::XMLInputArchive>(cereal::XMLInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccGdNoQ9.o: in function `void htm::SparseDistributedRepresentation::load_ar<cereal::PortableBinaryInputArchive>(cereal::PortableBinaryInputArchive&)':
/home/dave/htm.core/examp/../build/Debug/include/htm/types/Sdr.hpp:616: undefined reference to `htm::SparseDistributedRepresentation::initialize(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
/usr/bin/ld: /tmp/ccGdNoQ9.o:(.data.rel.ro._ZTVN3htm5ArrayE[_ZTVN3htm5ArrayE]+0x60): undefined reference to `htm::ArrayBase::allocateBuffer(std::vector<unsigned int, std::allocator<unsigned int> > const&)'
collect2: error: ld returned 1 exit status
```

I only get this when building with GCC in debug mode.
Release mode and anything on MSVC is fine.
Building in debug mode under CMake is fine too.

So I must be missing something but I don't know what or where.

**Comment by Zbysekz** [comment]
Ok, nice.


> So I must be missing something but I don't know what or where.

@dkeeney see your PR, i posted solution to this problem

**Comment by breznak** [comment]
Closing, this seems to have spawned into a PR that is already merged.
