### ISSUE TITLE
Deploy model on server

### ISSUE THREAD

**Issue by CharlesCamp** [htm-community/htm.core#891]
Hi everyone, I am trying to use this model for an app and am not sure what is the best approach to deploy it on a server. Do you have any recommendation ?

**Comment by breznak** [comment]
Hi, glad you're using our HTM! 

What precisely do you have in mind? 
I'd follow the instalation instructions, building either from source or PiPY is the most reliable option. 
If you need to repeatably and easily deploy, we have a Docker image. (Which is used for building ARM64, but can easily be modified for x64). 
Please be aware of the project's licence, AGPL. 

Cheers and let us know how's your app doing,

**Comment by CharlesCamp** [comment]
Basically, I would like to stream time series data and see their anomalies in my app. I imagine I would need to : 
1. Find a way to stream the data. River view is not an option as the data cannot be made available to the public.
2. Deploy the model to a server. I am currently looking at the REST API. I was thinking to deploy it on Heroku as it will probably make it easy to connect to DB afterwards.
Does it sound to you like the best option or am I missing something ? I was also wondering if I would need to wrap the model in Django or if the REST API provides all I need.

**Comment by CharlesCamp** [comment]
Also, I have little experience using web servers and keep getting this error while running : 
https://github.com/htm-community/htm.core/blob/master/py/htm/examples/hotgym.py 

Error : 
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8050): Max retries exceeded with url: /network (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e2c7610>: Failed to establish a new connection: [Errno 60] Operation timed out'))

**Comment by CharlesCamp** [comment]
I see in the comment of this file https://github.com/htm-community/htm.core/blob/master/py/htm/examples/client.py that we first need to start a server but what kind of server is it. How can I launch it locally ?

**Comment by CharlesCamp** [comment]
I finally used a docker image (not sure if this is the one you had in mind) https://3rdman.de/2020/02/using-the-htm-core-jupyter-docker-image/. That is the simplest way I found to have a server running. 
Regarding the client part, everything is explained here :  https://github.com/htm-community/htm.core/blob/master/docs/NetworkAPI.md 
Thanks a lot.

**Comment by breznak** [comment]
Good job, I'm glad you've managed to get all of that running yourself! :+1:
