### ISSUE TITLE
Master branch becomes Main branch

### ISSUE THREAD

**Issue by dkeeney** [htm-community/htm.core#892]
Starting Oct 1 2020, all master branches will be called main branches.

https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/?ftag=TRE20d3f17&bhid=25039841550920478664221329593539&mid=13070264&cid=712493651

**Comment by breznak** [comment]
this should not be any problem for us, it's just for new repos. Our workflow won't be changed.
