### ISSUE TITLE
setup.py errors from *.cpp files

### ISSUE THREAD

**Issue by aklandi** [htm-community/htm.core#893]
Hello,
I am using Anaconda3 on Windows 10 and I have Python 3.8.  I have successfully cloned the htm.core repository onto my computer, and I am at the step of `python setup.py install`.  I get far compared to previous attempts, but I am getting an error I cannot see others struggling with (it's below).  The text below "DateEncoder.cpp" is in red, while all other text appears in the standard color.  I am very confused because I am not using Visual Studio, but there seems to be some sort of issue with it.  I took a look at the `tolower` function in the errors, but it is formatted the same as other functions that are not throwing issues.  I'm not even sure the red error is the real issue.  Thank you in advance for your help.

DateEncoder.cpp
c:\users\l\htm.core\src\htm\encoders\dateencoder.cpp(121): error C2672: 'std::tolower': no matching overloaded function found [C:\Users\l\htm.core\build\scripts\src\LibrarySource.vcxproj]
c:\users\l\htm.core\src\htm\encoders\dateencoder.cpp(121): error C2780: '_Elem std::tolower(_Elem,const std::locale &)': expects 2 arguments - 1 provided [C:\Users\l\htm.core\build\scripts\src\LibrarySource.vcxproj]
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\locale(274): note: see declaration of 'std::tolower'

Traceback (most recent call last):
File "setup.py", line 374, in <module>
    getExtensionFiles(platform, build_type)
File "setup.py", line 239, in getExtensionFiles
    generateExtensions(platform, build_type)
File "setup.py", line 288, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type])
File "C:\Users\l\anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release']' returned non-zero exit status 1.

**Comment by dkeeney** [comment]
>  I am very confused because I am not using Visual Studio

It appears that you are using Visual Studio 2017.  I am not getting this error here locally so I don't know how I can help you.
I suggest trying to upgrade to Visual Studio 2019.  The community version is free.

**Comment by aklandi** [comment]
Thank you.  It seems that the programming in htm.core does require Visual Studio.  I have installed the community version 2019 alongside vs2017 and received the same error.  When I removed all instances of vs2017, this is the new error I get:

`Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]

CMake Error:
  Generator

    Visual Studio 15 2017 Win64

  could not find specified instance of Visual Studio:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools


Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    getExtensionFiles(platform, build_type)
  File "setup.py", line 239, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "setup.py", line 288, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type])
  File "C:\Users\l\anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release']' returned non-zero exit status 1.`

This implies that vs2017 buildtools is required.  So, I reinstall it (not easily available through the vs website for some reason, but I found it through [stackoverflow](https://stackoverflow.com/questions/57795314/are-visual-studio-2017-build-tools-still-available-for-download) with this [link](https://download.visualstudio.microsoft.com/download/pr/3e542575-929e-4297-b6c6-bef34d0ee648/639c868e1219c651793aff537a1d3b77/vs_buildtools.exe) ). 
However, I still received this error when running `python setup.py install`.

For one last attempt to solve the issue, I uninstalled htm.core and then reinstalled it by cloning from github.  I ran `python setup.py install`, and it ran successfully!  I even ran the tests, and 171 passed, 4 skipped, and this was all done in 88.64 seconds.

Thanks so much for your help!  Now I can attempt the examples and begin working on my own research problem.  Cheers.

**Comment by dkeeney** [comment]
Oh my...this is confusing everyone.
When running on windows, what setup.py does is first look for Visual Studio 2019.  If it does not find it, setup.py will then look for Visual Studio 2017.  If it cannot find either it gives the error "Did not find Microsoft Visual Studio 2017 or 2019."

setup.py does the looking by running "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe" and looking for the `displayName` field that contains 2017 or 2019.  So, it uses the one it finds as the 'generator'.
 So both VS 2017 and VS 2019 can coexist.

Now, If you tried to build and it gets part way there and fails, CMake leaves stuff in its cache and ignores any new values. 
So it is important to make sure that the `build` directory is deleted if you need to restart the build.
