### ISSUE TITLE
Permission denied error while running setup.py test

### ISSUE THREAD

**Issue by anjanapdas** [htm-community/htm.core#894]
am@TVM1263X:~/Anjana/htm.core-master$ python3 setup.py test

bindings/py/setup.py: Setup htm.core Python module in /home/am/Anjana/htm.core-master/build/Release/distr

/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing 'v2.1.15' to '2.1.15'
  normalized_version,
running test
running egg_info
writing src/htm.core.egg-info/PKG-INFO
writing dependency_links to src/htm.core.egg-info/dependency_links.txt
writing entry points to src/htm.core.egg-info/entry_points.txt
writing namespace_packages to src/htm.core.egg-info/namespace_packages.txt
writing requirements to src/htm.core.egg-info/requires.txt
writing top-level names to src/htm.core.egg-info/top_level.txt
reading manifest file 'src/htm.core.egg-info/SOURCES.txt'
writing manifest file 'src/htm.core.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/htm/dummy.cpython-36m-x86_64-linux-gnu.so -> src/htm
error: [Errno 13] Permission denied: '/home/am/Anjana/htm.core-master/build/Release/bin/unit_tests'

**Comment by breznak** [comment]
> copying build/lib.linux-x86_64-3.6/htm/dummy.cpython-36m-x86_64-linux-gnu.so -> src/htm
error: [Errno 13] Permission denied: '/home/am/Anjana/htm.core-master/build/Release/bin/unit_tests' 

this looks like a misconfiguration in your machine. 
Make sure you have `rwx` rights on the folder home/am/Anjana/htm.core-master/ (and all folders in it) 

Closing now, reopen if you have more details.
