### ISSUE TITLE
How to read data from mongodb instead of csv file?

### ISSUE THREAD

**Issue by anjanapdas** [htm-community/htm.core#895]

**Comment by breznak** [comment]
reading from mongoDB is not supported, as far as I know.

**Comment by anjanapdas** [comment]
Is it possible to read data from an array?

**Comment by dkeeney** [comment]
I assume you are talking about NetworkAPI.

The "FileInputRegion" can read from a file.  The file may be a binary array or a CSV formatted file.  There are variations on the expected arrangement of the data in the file.

There is also the "DatabaseRegion" which only supports writing to the internal SQLite3 database (intended for visualization).  I would love it if someone would like take on this project to expand this to do perform both input and output with any (or at least SQL) databases.

A third alternative is to feed the data directly to an input buffer using your app.  See the last section in the the [NetworkAPI_Links](https://github.com/htm-community/htm.core/blob/master/docs/NetworkAPI_Links.md) documentation.

**Comment by anjanapdas** [comment]
Its worked. thank you.
