### ISSUE TITLE
What are the essential files required to run just hotgym.py

### ISSUE THREAD

**Issue by kunkub** [htm-community/htm.core#896]

**Comment by dkeeney** [comment]
I assume you are talking about the "prerequisites" for running the Python implementation of hotgym.
1) you will need Python.  I recommend the latest Python from python.org.
2) you will need the htm.core library installed in python. This will also install all prerequisites. I recommend using `python setup.py install`  which will build from sources.
3) The data is found in gymdata.csv in the same folder as hotgym.py.

**Comment by kunkub** [comment]
So, after build , I can run just hotgym.py anywhere in the machine?

**Comment by kunkub** [comment]
what about other dependent files like bindings , encoder, etc?

**Comment by dkeeney** [comment]
When you do the build (python setup.py install) the bindings and all dependencies are installed into python.  To run, cd to the examples folder containing hotgym.py.  Type `python3 hotgym.py`.  It will open the data file which it expects to find in the same folder.

**Comment by kunkub** [comment]
thanks
