### ISSUE TITLE
ScalarEncoder Errors

### ISSUE THREAD

**Issue by aklandi** [htm-community/htm.core#900]
Hello,

I am simply attempting to encode a scalar so I can understand how to adapt nupic's AdaptiveScalarEncoder for htm.core.  I am using a Windows 10 machine, Anaconda 3, and Pyzo as my IDE.

`from htm.bindings.encoders import ScalarEncoder`
`enc = ScalarEncoder(size = 22, activeBits =3, minimum =2.5, maximum = 97.5)`

Importing is successful, but when I attempt to initialize the encoder, I get the following error:

`Traceback (most recent call last):`
  `File "<console>", line 1, in <module>`
`TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:`
    `1. htm.bindings.encoders.ScalarEncoder(arg0: htm.bindings.encoders.ScalarEncoderParameters)`
`Invoked with: kwargs: size=22, activeBits=3, minimum=2.5, maximum=97.5`

I'm not sure what this means since I am following documentation for the parameters (available through `python -m htm.examples.encoders.scalar_encoder --help`).  Any help is welcome and appreciated.

**Comment by dkeeney** [comment]
The class `ScalarEncoder` is constructed with the one argument `ScalarEncoderParameters`.  It is `ScalarEncoderParameters` that needs the parameters.
```
scalarEncoderParams    = ScalarEncoderParameters()
scalarEncoderParams.size = 22
scalarEncoderParams.activeBits = 3
scalarEncoderParams.minimum = 2.5
scalarEncoderParams.maximum = 97.5
encoder = ScalarEncoder(scalarEncoderParams)
```
