### ISSUE TITLE
install htm.core in windows10, gaven this error message:

### ISSUE THREAD

**Issue by fenfeibani** [htm-community/htm.core#901]
PS D:\Python39\Scripts> pip install -i https://test.pypi.org/simple/htm.core
ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by SethFogg** [comment]
There is a space after /simple/ and before htm.core. The command is:
`pip install -i https://test.pypi.org/simple/ htm.core`

**Comment by breznak** [comment]
Thanks @SethFogg for answering the user's problem! 
Closing as resolved.
