### ISSUE TITLE
how to use multi encoder in htm?

### ISSUE THREAD

**Issue by kunkub** [htm-community/htm.core#903]
Need to know, how data from multiple sources feed to htm?

**Comment by dkeeney** [comment]
Ok, lets take the DateEncoder as the example.  See src/htm/encoders/DateEncoder.cpp
This can combine inputs for 

- Season
- Day of week
- Weekend
- Custom days (a set of days in the week, like Mon, Wed, Fri)
- Holidays 
- Time of day

For each input, a separate ScalarEncoder object is created, each creating an SDR.  Then all of the SDR's are concatenated.  this means that the range of bits for each encoder are arranged next to each other but they do not overlap.  Then this concatenated SDR is passed to a SpatialPooler to make it sparse.

This can be applied to any set of inputs. Encode each input separately and then combine the results such that each encoder's output takes up a range of bits that are next to each other but not overlapping.

For example, lets say we have two inputs.  The first uses a set of 5 bits to encode.  The second uses a set of 7 bits to encode.  The concatenation would put the first encoder's output in bits 0 through 4. The second would be placed in bits 5 through 11.  This establishes the Semantics.  It is then passed to the SpatialPooler to make it sparse.

**Comment by kroggen** [comment]
There is a visual example for datetime encoding on this video:

https://www.youtube.com/watch?v=PTYlge2K1G8

**Comment by kunkub** [comment]
Thank You. I did it. works fine.
