### ISSUE TITLE
Building HTM in ubuntu 16

### ISSUE THREAD

**Issue by kunkub** [htm-community/htm.core#904]
I am getting gcc compiler error whiling trying to build HTM core in ubuntu 16. Please support me to solve the issue.

**Comment by dkeeney** [comment]
Can you give me a hint as to what the compiler error was and where it occurred?

**Comment by kunkub** [comment]
It seems like, it may not support gcc 5 in ubuntu 16.04. Any option to solve this issue?  Not able to upgrade OS now since other applications running parallel y

**Comment by dkeeney** [comment]
I don't happened to have ubuntu 16.04 available but I do have ubuntu 20.04 which is using GNU 10 compiler.

I do get an error I have not seen before. It gets this when constructing the shared library.
```
[ 32%] Linking CXX shared library libhtm_core.so
lto1: internal compiler error: bytecode stream: expected tag identifier_node instead of LTO_UNKNOWN
```

Is this what you are seeing?

**Comment by kunkub** [comment]
No. it is like gcc version mismatch. 
Earlier I build it in ubuntu 20. No isssues. Working fine. 
But not able to do it in 16.04. Dont know how to solve this. Still struggling.

**Comment by breznak** [comment]
Ubuntu 18.04 and 20.04 are supported and would work fine. I'm certain you can run HTMcore on ubuntu 16.04 but meeting the requirements would require some setup. 
Closing as an old issue.
