### ISSUE TITLE
inhibitColumns returns uninitialized value

### ISSUE THREAD

**Issue by surenreddy** [htm-community/htm.core#908]
It seems a bug in` inhibitColumns` function in py_SpatialPooler.cpp 
This function is returning uninitialized value.

https://github.com/htm-community/htm.core/blob/3061c9863fc96e79f45b90d834828adbde1e80fa/bindings/py/cpp_src/bindings/algorithms/py_SpatialPooler.cpp#L411

I have modified it as follows. it worked...
auto activeColumnsVector = self.inhibitColumns_(overlapsVector);

Regards,
Surendra

**Comment by dkeeney** [comment]
Thank you.  I will take a look at it when I return from the holidays.

**Comment by dkeeney** [comment]
Addressed in Pull Request #909

**Comment by breznak** [comment]
Thank you @dkeeney , I think this can now be closed. 
Reopen if needed.
