### ISSUE TITLE
Build error...

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#919]
Dear all
I have just installed Ubuntu 20.04 LTS in my new laptop and downloaded the current version htm.core.
I have the following errors
[ 97%] Linking CXX executable mnist_example
/usr/bin/ld: CMakeFiles/mnist_example.dir/main.cpp.o: in function `mnist::MNIST_dataset<std::vector, std::vector<unsigned char, std::allocator<unsigned char> >, unsigned char>::~MNIST_dataset()':
main.cpp:(.text._ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED2Ev[_ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED5Ev]+0x15): undefined reference to `operator delete(void*)'
/usr/bin/ld: main.cpp:(.text._ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED2Ev[_ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED5Ev]+0x23): undefined reference to `operator delete(void*)'
/usr/bin/ld: main.cpp:(.text._ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED2Ev[_ZN5mnist13MNIST_datasetISt6vectorS1_IhSaIhEEhED5Ev]+0x42): undefined reference to `operator delete(void*)'

Does anybody knows this problem?
Thanks

**Comment by dkeeney** [comment]
Hmmm, I cloned and built htm.core here on Windows 10 earlier today and it built correctly.  I will try it on Ubuntu 20.04,,,
Building with Python 38;   `python3 setup.py install --user --force`
Running Unit tests:     python3 setup.py test
Everything ran fine.

The build actually happens in two phases.  The first phase downloads and builds the Third party dependencies.  The second actually builds the htm.core library.  Once the dependencies are downloaded and built they are not re-built even if you pull changes from the repository or make changes to the Third Party code.  So, here is what I suggest:
- Delete the entire build folder
- repeat the build with `python3 setup.py install`   (with --user and --force if needed)
The error you had was something in MNIST which is one of those dependencies. This will re-generate all of the dependencies. 

I hope that helped.


.

**Comment by Thanh-Binh** [comment]
I found for testing it we need to link to -lstdc++, but I do know where is the best place for inserting this link...

**Comment by Thanh-Binh** [comment]
@dkeeney I found this problem in my new laptop where libstdcc was installed after the first call of cmake, that created ThirdParty and configured them to compile using gcc.
After deleting the folder ThirdParty and run cmake again I can solve this problem.
Thanks

**Comment by dkeeney** [comment]
Not sure what you are saying...
The libstdcc for gcc is specified in CommonCompilerConfig.cmake line 261
After returning from this, the variable COMMON_OS_LIBS should contain all of the operating system specific link options that are being used.  You can check that to see if it has the right things for your environment.
