### ISSUE TITLE
Memory Leakage in TM

### ISSUE THREAD

**Issue by ZhekaHauska** [htm-community/htm.core#925]
I have found that memory usage by Temporal Memory increases during learning a random sequence(or a relatively complex), though I set `maxSegmentsPerCell=2`. I run the last version of `htm.core` from the github. It seems like the segment destroyer is not working properly because I have found the same issue using `Connections` in my TM implementation. Probably this issue is connected with https://github.com/htm-community/htm.core/issues/911.

To reproduce the problem, I run this example:
 
```
import numpy as np
from htm.bindings.sdr import SDR
from htm.bindings.algorithms import TemporalMemory


max_number = 5
bucket_size = 10


def encode(x, bucket_size):
    return np.arange(bucket_size*x, bucket_size*(x+1))


tm = TemporalMemory(columnDimensions=(bucket_size*max_number, ),
                    cellsPerColumn=3,
                    activationThreshold=bucket_size,
                    minThreshold=bucket_size,
                    initialPermanence=0.4,
                    connectedPermanence=0.5,
                    maxNewSynapseCount=bucket_size,
                    maxSynapsesPerSegment=bucket_size,
                    permanenceIncrement=0.1,
                    permanenceDecrement=0.02,
                    predictedSegmentDecrement=0.001,
                    maxSegmentsPerCell=2
                    )


sdr = SDR(bucket_size*max_number)

for _ in range(100000):
    # tm.reset()
    x = np.random.randint(0, max_number)
    sdr.sparse = encode(x, bucket_size)
    tm.compute(sdr, learn=True)
    tm.activateDendrites(learn=True)
print('done')
```
And getting this memory profile:

![изображение](https://user-images.githubusercontent.com/47570311/115066936-e2dacc00-9ef8-11eb-8169-85161a4db24d.png)

**Comment by ctrl-z-9000-times** [comment]
Hi,

Could you please check that you're running the latest version from github?
I recently fixed an issue were segments were not being destroyed & reused,
and that fix was merged into the main branch only about 24 hours ago.

Thanks

**Comment by ZhekaHauska** [comment]
I have built the last version from github, and the issue is gone. Thanks!
![image](https://user-images.githubusercontent.com/47570311/115104592-2f0e2680-9f62-11eb-98b8-9ea078a44ba6.png)
