### ISSUE TITLE
python setup.py install

### ISSUE THREAD

**Issue by qiezikuangge** [htm-community/htm.core#926]
SdrMetrics.cpp
  Topology.cpp
Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    getExtensionFiles(platform, build_type)
  File "setup.py", line 239, in getExtensionFiles
    generateExtensions(platform, build_type)
  File "setup.py", line 288, in generateExtensions
    subprocess.check_call(["cmake", "--build", ".", "--target", "install", "--config", build_type])
  File "D:\Anaconda\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release']' returned non-zero exit status 1.
Execute install error when compiling some .cpp. Please help

**Comment by dkeeney** [comment]
First I need to know your environment.  Windows, Linux, or OSx
What version of your OS are you running?
What version of CMake do you have installed?

**Comment by qiezikuangge** [comment]
> First I need to know your environment. Windows, Linux, or OSx
> What version of your OS are you running?
> What version of CMake do you have installed?

Thanks for the reply, I use "pip install" sucessed
