### ISSUE TITLE
Question about python development mode

### ISSUE THREAD

**Issue by phukfs** [htm-community/htm.core#936]
I am having trouble finding the distr scripts that I can edit to change the htm.core algorithms. When i import modules such as htm.bindings.sdr and run print(htm.bindings.sdr.__file__) it lists a gnu.so file and not editable scripts

Any help would be greatly appreciated.

**Comment by phukfs** [comment]
To clarify, I am looking to invesitgate alternate methods of choosing the active connections in the SpatialPooler class and am unsure how to go about this

**Comment by ctrl-z-9000-times** [comment]
Hi,

Everything in the `htm.bindings` module is written in C++, including the `SDR`, `SpatialPooler` and `Connections` classes.
Sorry, to edit the SP requires compiling the C++ source code.

**Comment by phukfs** [comment]
Ah ok, thanks for the reply. Is there a quick way to just recompile individual C++ files or will I need to recompile the entirety of htm.core for every change? Im not too familiar with C++ so sorry if thats a stupid question

**Comment by dkeeney** [comment]
The build process is built on CMake.  When a build is kicked off it will look through the library source files and re-compile any that have changed and then rebuild the libraries and the example and test programs.  Yes this does take a long time to build but the result will execute faster than similar code written in Python.

**Comment by phukfs** [comment]
Perfect, thanks for the help everyone. I will mark this as closed now.
