### ISSUE TITLE
Can't install on linux following tutorial in README

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#937]
I tried to install `htm.core` following installation tutorial with pip:
```
$ pip install -i https://test.pypi.org/simple/ htm.core
Looking in indexes: https://test.pypi.org/simple/
Collecting htm.core
  Downloading https://test-files.pythonhosted.org/packages/db/71/6ab3ea6b98e3de12d43387a590f922917e9dfab08147000b8fdef1aa86ae/htm.core-2.1.15-cp37-cp37m-manylinux2014_x86_64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 4.7 MB/s 
ERROR: Could not find a version that satisfies the requirement mock>=1.0.1 (from htm.core) (from versions: none)
ERROR: No matching distribution found for mock>=1.0.1 (from htm.core)
```
I think it happened because it's on test index. Why it's not hosted on main index, pypi.org?
I was able to install by downloading wheel file then installing it _without_ setting index to test.pypi.org:
```
$ wget https://test-files.pythonhosted.org/packages/db/71/6ab3ea6b98e3de12d43387a590f922917e9dfab08147000b8fdef1aa86ae/htm.core-2.1.15-cp37-cp37m-manylinux2014_x86_64.whl
$ pip install htm.core-2.1.15-cp37-cp37m-manylinux2014_x86_64.whl
```
Also there is no distribution for Python 3.8 on pypi. But #820 did not solved it?

I am on Ubuntu 18.04. Thanks.

**Comment by HMaker** [comment]
> If you want to use htm.core from Python, the easiest method is to install from PyPI
Note: to install from pip you'll need Python 3.7+
python -m pip install -i https://test.pypi.org/simple/ htm.core

Does "Python 3.7+" means "Python >= 3.7"? If yes I think it's misleading since there is only distribution for Python 3.7 on pypi.

**Comment by zrosin** [comment]
I believe the pip install is not working at the moment. I had to follow the directions to install from source.

**Comment by HMaker** [comment]
It works, the problem is that `htm.core` distribution is hosted on test repository of pypi (test.pypi.org), then pip will try to search dependencies there if you pass `-i https://test.pypi.org/simple/`, the workaround for that is download wheel file then install it.

**Comment by HMaker** [comment]
#943 is going forward on this issue.
