### ISSUE TITLE
ScalarEncoderRegion does not takes sparsity neither category parameters through Network API

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#939]
I tried to add a `ScalarEncoderRegion` to the network with
```python
from htm.bindings.engine_internal import Network

net = Network()
my_input = net.addRegion(
    'myInputEncoder',
    'ScalarEncoderRegion',
    str(dict(minimum=0, maximum=65, size=700, sparsity=0.02))
)
```
but it raises `RuntimeError: Exception: ScalarEncoder.cpp(41) message: CHECK FAILED: "num_active_args != 0u" Missing argument, need one of: 'activeBits' or 'sparsity'.`

https://github.com/htm-community/htm.core/blob/766368acce3ea354a94c9fd9c83994b0f4066a69/src/htm/encoders/ScalarEncoder.cpp#L33-L43

so it looks like sparsity parameter is not being passed to C++.

Computing `activeBits` manually works:
```python
from htm.bindings.engine_internal import Network

net = Network()
my_input = net.addRegion(
    'myInputEncoder',
    'ScalarEncoderRegion',
    str(dict(minimum=0, maximum=65, size=700, activeBits=700 * 0.02))
)
```

**Comment by HMaker** [comment]
```python
from htm.bindings.engine_internal import Network

net = Network()
my_input = net.addRegion(
    'myInputEncoder',
    'ScalarEncoderRegion',
    str(dict(minimum=0, maximum=65, activeBits=700 * 0.02, category=True))
)
```
fails with `RuntimeError: Exception: ScalarEncoder.cpp(51) message: CHECK FAILED: "num_size_args != 0u" Missing argument, need one of: 'size', 'radius', 'resolution', 'category'.`. As error message says, it asks for one of them, but category was given.

**Comment by dkeeney** [comment]
This looks like something I should investigate. 
I am traveling at the moment but I will try to work on this within the next few days.

**Comment by HMaker** [comment]
Hey @dkeeney I am using htm.core v2.1.15, maybe that does not happens on master branch. Also I found another problem, Predictor is not pickable on that branch too, looks like master branch is far ahead of v2.1.15.

**Comment by HMaker** [comment]
I checked on master branch, it happens there too. These parameters seems to be handled properly for `RDSEncoderRegion`, it's the one used in hotgym example.

**Comment by dkeeney** [comment]
I am back home where I can work on it...
You are correct.  The NetworkAPI wrapper ScalarEncoderRegion did not pick up 'category' or 'sparsity' parameters. Good catch.

I am making the correction.

**Comment by dkeeney** [comment]
@HMaker The ScalerEncoderRegion has been updated.  Please clone another copy of the repository and rebuild the library.
Thanks again for pointing this out.

**Comment by HMaker** [comment]
Thanks for your work on this.
