### ISSUE TITLE
Can't access encoder wrapped by ScalarEncoderRegion

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#940]
I need to call `scalarEncoder.getBucketIndices()` using `ScalarEncoderRegion` but that's not possible since `ScalarEncoderRegion.getSelf()` is not implemented and from what I saw at #610 won't be. So is there a way to interact with the wrapped encoder? There are a lot of Network API code from nupic that uses `getSelf()`.

**Comment by dkeeney** [comment]
Well, there is the `executeCommand( )` facility.  It is not as useful as getSelf( ) but depending on what it is trying to do it might work.

If you are willing to work with me on this perhaps we can come up with something that will work for you.

**Comment by HMaker** [comment]
Hey @dkeeney , I could work but I don't understand yet how `htm.core` works internally, I started using it few days ago. I found I can compute bucket index by taking encoder resolution with `int(inputValue / encoderRegion.getParameterReal64("resolution"))`, it requires me to re-implement `ScalarEncoder.getBucketIndices()` because I can't call it through regions.

If regions are a wrapper why not all public methods of wrapped object are exposed? I tried `encoderRegion.executeCommand("getBucketIndices")` but it did not work, is that `executeCommand` a way to call methods on wrapped encoder?

**Comment by HMaker** [comment]
Same problem for `TemporalMemoryRegion`, I can't call `TemporalMemory.getActiveCells()`. Is there a way to call it?

Looks like Network API is incompatible with "manual mode" of building HTM network.

**Comment by dkeeney** [comment]
First of all, the getBucketIndices( ) function does not exist on the ScalarEncoder class in htm.core.  The encoder is implemented in C++ so there is no Python object pointer to return with a getSelf( ).  We could hack up a dummy one but getSelf( ) would still break the plugin interface as explained in #610.  

But, do you really need it? As you found, you can compute the bucket yourself when using the ScalarEncoder directly by dividing by the resolution.

When using ScalarEncoderRegion in the NetworkAPI it is more difficult to compute it yourself so there is an output which contains the quantized version of the encoded value (which is the bucket value).  See the 'bucket' output.  This can be hooked up to the SDRClassifierRegion for use in training.

So, do you really need getBucketIndeces( ) ?

**Comment by HMaker** [comment]
Ok, in this case yes I can, but was I said if Region objects just wraps another one to make it compatible with network objects, why not also expose public methods of that wrapped object throught Region interface? Anyway I will close it, thanks.

**Comment by dkeeney** [comment]
@HMaker  the point is that getBucketIndices( ) is not a public method on the wrapped object ScalarEncoder.  It does not exist.

Also, it is actually not quite as simple as a wrapped object.  The Region wraps the plugin interface which is common for all regions.  The Region object uses the plugin interface to call the ScalarEncoderRegion which then wraps ScalarEncoder.
