### ISSUE TITLE
Can saveToFile() be called on MemoryError?

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#944]
I am running an HTM architecture like `10 encoders -> 1 SP -> 1 TM -> 5 1-step predictors (5 internal classifiers)`, sometimes suddenly RAM usage increases and hits 7GB limit I have set, then `MemoryError` is raised. In that cases I save model to file and restart it right after, and the RAM usage does not increases anymore even same stream size and rate being feed into it.

So I am wondering if I am saving a corrupted model since `MemoryError` may be raised in middle of SP or TM algorithm execution.

**Comment by Thanh-Binh** [comment]
@HMaker I really do not have any memory problem. I believe it’s your own codes problem!

**Comment by HMaker** [comment]
I am sure it's not my code. Have you tried using 10 encoders and predict next value for 5 of them?
