### ISSUE TITLE
Boost download URL is broken

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#946]
Some days ago I tried to build `htm.core` from source on Ubuntu 18.04, but boost download URL was broken, I was getting HTTP Forbidden errors. The download URL is this:
https://github.com/htm-community/htm.core/blob/6483a497690449ec7a647226bc22993e9e987740/external/Boost.cmake#L33-L39

On my local clone I changed it to `https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz`, that's the download URL found at https://www.boost.org/users/download/

**Comment by dkeeney** [comment]
Good catch.  They must have changed where they hosted the Boost download.
I will change the URL and update to 1.76.0 as well.

By the way, if you update to the GCC 8 compiler  on Ubuntu 18.04 the htm.core build will not need Boost at all.
Boost takes so long to download.

**Comment by ctrl-z-9000-times** [comment]
Ok, I merge the fix for the new URL for boost downloads.
Thank you for reporting this and suggesting a fix.
