### ISSUE TITLE
NetworkAPI_Regions docfile has one flaw

### ISSUE THREAD

**Issue by zengwufu** [htm-community/htm.core#953]
the type of the param named "learningMode" in SPRegion build in Network API should be "Uint32", but the markdown file of NetworkAPI_Regions told it belong "Boolean".

**print(spRegion.getParameterBool("learningMode"))**
there is exception info:
RuntimeError: Exception: RegionImpl.cpp(72) message: getParameterbool: Region type SPRegion, parameter learningMode is of type UInt32 not  #bool

**Comment by dkeeney** [comment]
You are absolutely correct.  Thank you for catching that.  I will make the change in the documentation.
