### ISSUE TITLE
Build with Xcode 13.3.x fails with DEPRECATED error

### ISSUE THREAD

**Issue by fcr** [htm-community/htm.core#981]
Building htm.core with Xcode 13.3 or 13.3.1 fails with a DEPRECATED error. Xcode 13.2 works fine.
I've attached a partial console output:
[xcode 13.3.1 error.txt](https://github.com/htm-community/htm.core/files/8478545/xcode.13.3.1.error.txt)
.
Build is run on Monterey 12.3.1 with Anaconda Python 3.9

If the change [posted](https://github.com/htm-community/htm.core/issues/975#issuecomment-1089553785) by @[finnoshea](https://github.com/finnoshea) is used, then the build with Xcode 13.3.1 succeeds and passes all unit tests.

**Comment by ctrl-z-9000-times** [comment]
I think PR #974 should fix this issue.

**Comment by fcr** [comment]
Great. Thanks.

**Comment by fcr** [comment]
> I think PR #974 should fix this issue.

I am sorry to say that it didn't. 
I still had to apply the change change https://github.com/htm-community/htm.core/issues/975#issuecomment-1089553785 by @[finnoshea](https://github.com/finnoshea) in order to build.

**Comment by ctrl-z-9000-times** [comment]
Okay, thanks for reporting back to me about that.

1) PR#974 removed the file that was causing the error in the log that you posted, so I'm assuming that now you're hitting another error.  

2) I'm going to see about pulling finnoshea's fix (removing the `-werror` flag) into the main line...

**Comment by fcr** [comment]
Just for the record, this is the new error message. It seems that as long as the `-Werror` flag is used, its a game of "Wack a Mole" 
[xcode 13.3.1 error2.txt](https://github.com/htm-community/htm.core/files/8489043/xcode.13.3.1.error2.txt)

**Comment by dkeeney** [comment]
The objective of the -Werror flag was to force us to fix all (or at least most) of the warnings.  I admit that some of the warnings we are now seeing may not really have a 'fix'.  But I would try to avoid turning off -Werror everywhere.

**Comment by ctrl-z-9000-times** [comment]
See PR #982 

The compromise that I've implemented in that PR is to enable the -Werror flag for Debug mode builds, but not for Release mode builds.

**Comment by fcr** [comment]
> The compromise that I've implemented in that PR is to enable the -Werror flag for Debug mode builds, but not for Release mode builds.

That solves this issue.
