### ISSUE TITLE
'cp950' codec can't decode

### ISSUE THREAD

**Issue by r1235613** [htm-community/htm.core#989]
Hi,
The error `'cp950' codec can't decode` happened when I tryy to install from source code.
And I fixed with change:
https://github.com/htm-community/htm.core/blob/master/setup.py#L416
`with open(os.path.join(REPO_DIR, "README.md"), "r") as fh:`
to
`with open(os.path.join(REPO_DIR, "README.md"), "r", encoding="utf-8") as fh:`

**Comment by dkeeney** [comment]
Suggestion approved.  Thanks you for bringing this to our attention.
