### ISSUE TITLE
Debian installation attempt fails: ModuleNotFoundError: No module named 'htm.bindings'

### ISSUE THREAD

**Issue by RandySaint** [htm-community/htm.core#996]
Debian 5.10.162-1
Python 3.9.2
Following the readme, did a git clone of htm.core

python setup.py install --user --force
Completed without errors.

To check it tried this in python.
python
```
>>> import htm
>>> import htm.bindings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'htm.bindings'
>>>
``` 

Running htm-bindings-check, i get:

Traceback (most recent call last):
  File "/home/ramdu/.local/bin/htm-bindings-check", line 33, in <module>
    sys.exit(load_entry_point('htm.core==2.1.16', 'console_scripts', 'htm-bindings-check')())
  File "/home/ramdu/.local/bin/htm-bindings-check", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'htm.bindings'

I'm not sure if this is an htm.core issue or something I've got wrong in my configuration.

Thanks in advance for any help.

**Comment by ctrl-z-9000-times** [comment]
I think this means that it didn't compile and install the underlying C++ library.
When you installed it did it run cmake for about 5-10 minutes?

**Comment by RandySaint** [comment]
Yes, it did. Is there some way I can check the directory or a log file?

**Comment by ctrl-z-9000-times** [comment]
This problem pops up from time to time, and I honestly forgot how to fix it...

The cmake script should put the python files at:
`repo/build/Release/distr/src/`

If you go to that directory and run python you should be able to `import htm.bindings` as a local file (without installing it for the whole system).


The command that I personally use to build this library is:
```
pushd build/scripts ; cmake ../.. -DCMAKE_INSTALL_PREFIX=../Release -DCMAKE_BUILD_TYPE=Release && make VERBOSE=1 install -j 6 ; popd ;
py3 setup.py install --user --force
```

**Comment by RandySaint** [comment]
Thanks for the info.  If I run in that directory, I don't see the error with `import htm.bindings` from python.

The command line you showed there works (seems to go through everything with no error), but I still get the error with htm.bindings if I'm not in the Release/distr/src/ directory.

**Comment by ctrl-z-9000-times** [comment]
As a quick fix, i recommend either manually copying the file to python's "site-package" directory, or making a symbolic link.

This is what worked on my linux computer:
```
cd htm.core/build/Release/distr/dist
ls
```
You should see an ".egg" file named something like "htm.core-2.1.16-py3.10-linux-x86_64.egg"
Unzip the ".egg" file.
It should contain a directory named "htm" which includes the bindings.
```
unzip htm.core-2.1.16-py3.10-linux-x86_64.egg
mv htm ~/.local/lib/python3.10/site-packages/
```

**Comment by RandySaint** [comment]
That works.  Thanks for the workaround.
